/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: OakProfile.proto */

#ifndef PROTOBUF_C_OakProfile_2eproto__INCLUDED
#define PROTOBUF_C_OakProfile_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "OakShared.pb-c.h"

typedef struct _OakSave__PlayerInputBindingButton OakSave__PlayerInputBindingButton;
typedef struct _OakSave__PlayerInputBindingAxisKey OakSave__PlayerInputBindingAxisKey;
typedef struct _OakSave__PlayerInputBindingAxis OakSave__PlayerInputBindingAxis;
typedef struct _OakSave__PlayerInputBindingCategory OakSave__PlayerInputBindingCategory;
typedef struct _OakSave__PlayerInputBindings OakSave__PlayerInputBindings;
typedef struct _OakSave__OakProfileLastInventoryFilterInfo OakSave__OakProfileLastInventoryFilterInfo;
typedef struct _OakSave__OakProfileMenuTutorialInfo OakSave__OakProfileMenuTutorialInfo;
typedef struct _OakSave__OakFriendEncounterData OakSave__OakFriendEncounterData;
typedef struct _OakSave__OakMailItem OakSave__OakMailItem;
typedef struct _OakSave__GearSoldByFriendData OakSave__GearSoldByFriendData;
typedef struct _OakSave__OakCustomizationSaveGameData OakSave__OakCustomizationSaveGameData;
typedef struct _OakSave__OakInventoryCustomizationPartInfo OakSave__OakInventoryCustomizationPartInfo;
typedef struct _OakSave__GuardianRankRewardSaveGameData OakSave__GuardianRankRewardSaveGameData;
typedef struct _OakSave__GuardianRankProfileData OakSave__GuardianRankProfileData;
typedef struct _OakSave__CrewQuartersDecorationItemSaveGameData OakSave__CrewQuartersDecorationItemSaveGameData;
typedef struct _OakSave__CrewQuartersRoomItemSaveGameData OakSave__CrewQuartersRoomItemSaveGameData;
typedef struct _OakSave__RecentlyMetPlayer OakSave__RecentlyMetPlayer;
typedef struct _OakSave__Profile OakSave__Profile;
typedef struct _OakSave__Profile__FriendEncountersEntry OakSave__Profile__FriendEncountersEntry;


/* --- enums --- */


/* --- messages --- */

struct  _OakSave__PlayerInputBindingButton
{
  ProtobufCMessage base;
  char *rebind_data_path;
  size_t n_key_names;
  char **key_names;
};
#define OAK_SAVE__PLAYER_INPUT_BINDING__BUTTON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__player_input_binding__button__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _OakSave__PlayerInputBindingAxisKey
{
  ProtobufCMessage base;
  char *key_name;
  OakSave__Vec3 *scale_3d;
};
#define OAK_SAVE__PLAYER_INPUT_BINDING__AXIS__KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__player_input_binding__axis__key__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  _OakSave__PlayerInputBindingAxis
{
  ProtobufCMessage base;
  char *rebind_data_path;
  size_t n_keys;
  OakSave__PlayerInputBindingAxisKey **keys;
};
#define OAK_SAVE__PLAYER_INPUT_BINDING__AXIS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__player_input_binding__axis__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _OakSave__PlayerInputBindingCategory
{
  ProtobufCMessage base;
  char *category_data_path;
  char *context_data_path;
  size_t n_button_bindings;
  OakSave__PlayerInputBindingButton **button_bindings;
  size_t n_axis_bindings;
  OakSave__PlayerInputBindingAxis **axis_bindings;
};
#define OAK_SAVE__PLAYER_INPUT_BINDING__CATEGORY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__player_input_binding__category__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL }


struct  _OakSave__PlayerInputBindings
{
  ProtobufCMessage base;
  size_t n_categories;
  OakSave__PlayerInputBindingCategory **categories;
};
#define OAK_SAVE__PLAYER_INPUT_BINDINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__player_input_bindings__descriptor) \
    , 0,NULL }


struct  _OakSave__OakProfileLastInventoryFilterInfo
{
  ProtobufCMessage base;
  char *slot_type_id;
  int32_t last_filter_index;
};
#define OAK_SAVE__OAK_PROFILE_LAST_INVENTORY_FILTER_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_profile_last_inventory_filter_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__OakProfileMenuTutorialInfo
{
  ProtobufCMessage base;
  size_t n_seen_tutorials;
  char **seen_tutorials;
  protobuf_c_boolean tutorials_disabled;
  protobuf_c_boolean tutorials_allowed_in_non_game_modes;
};
#define OAK_SAVE__OAK_PROFILE_MENU_TUTORIAL_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_profile_menu_tutorial_info__descriptor) \
    , 0,NULL, 0, 0 }


struct  _OakSave__OakFriendEncounterData
{
  ProtobufCMessage base;
  uint32_t num_encounters;
  int64_t time_last_encounter;
};
#define OAK_SAVE__OAK_FRIEND_ENCOUNTER_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_friend_encounter_data__descriptor) \
    , 0, 0 }


struct  _OakSave__OakMailItem
{
  ProtobufCMessage base;
  uint32_t mail_item_type;
  char *sender_display_name;
  char *subject;
  char *body;
  char *gear_serial_number;
  char *mail_guid;
  int64_t date_sent;
  int64_t expiration_date;
  char *from_player_id;
  protobuf_c_boolean has_been_read;
};
#define OAK_SAVE__OAK_MAIL_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_mail_item__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__GearSoldByFriendData
{
  ProtobufCMessage base;
  char *gear_serial_number;
  int32_t player_class_identifier_hash;
  char *friend_net_id;
};
#define OAK_SAVE__GEAR_SOLD_BY_FRIEND_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__gear_sold_by_friend_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  _OakSave__OakCustomizationSaveGameData
{
  ProtobufCMessage base;
  protobuf_c_boolean is_new;
  char *customization_asset_path;
};
#define OAK_SAVE__OAK_CUSTOMIZATION_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_customization_save_game_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__OakInventoryCustomizationPartInfo
{
  ProtobufCMessage base;
  uint32_t customization_part_hash;
  protobuf_c_boolean is_new;
};
#define OAK_SAVE__OAK_INVENTORY_CUSTOMIZATION_PART_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_inventory_customization_part_info__descriptor) \
    , 0, 0 }


struct  _OakSave__GuardianRankRewardSaveGameData
{
  ProtobufCMessage base;
  int32_t num_tokens;
  char *reward_data_path;
};
#define OAK_SAVE__GUARDIAN_RANK_REWARD_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__guardian_rank_reward_save_game_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__GuardianRankProfileData
{
  ProtobufCMessage base;
  int32_t available_tokens;
  size_t n_rank_rewards;
  OakSave__GuardianRankRewardSaveGameData **rank_rewards;
  int32_t guardian_rank;
  int32_t guardian_experience;
  int32_t guardian_reward_random_seed;
  int64_t new_guardian_experience;
};
#define OAK_SAVE__GUARDIAN_RANK_PROFILE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__guardian_rank_profile_data__descriptor) \
    , 0, 0,NULL, 0, 0, 0, 0 }


struct  _OakSave__CrewQuartersDecorationItemSaveGameData
{
  ProtobufCMessage base;
  protobuf_c_boolean is_new;
  char *decoration_item_asset_path;
};
#define OAK_SAVE__CREW_QUARTERS_DECORATION_ITEM_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__crew_quarters_decoration_item_save_game_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__CrewQuartersRoomItemSaveGameData
{
  ProtobufCMessage base;
  protobuf_c_boolean is_new;
  char *room_item_asset_path;
};
#define OAK_SAVE__CREW_QUARTERS_ROOM_ITEM_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__crew_quarters_room_item_save_game_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__RecentlyMetPlayer
{
  ProtobufCMessage base;
  char *shift_player_id;
  char *first_party_player_id;
  protobuf_c_boolean show_shift_player_entry;
};
#define OAK_SAVE__RECENTLY_MET_PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__recently_met_player__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__Profile__FriendEncountersEntry
{
  ProtobufCMessage base;
  char *key;
  OakSave__OakFriendEncounterData *value;
};
#define OAK_SAVE__PROFILE__FRIEND_ENCOUNTERS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__profile__friend_encounters_entry__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  _OakSave__Profile
{
  ProtobufCMessage base;
  protobuf_c_boolean enable_aim_assist;
  protobuf_c_boolean gamepad_invert_look;
  protobuf_c_boolean gamepad_invert_turn;
  protobuf_c_boolean gamepad_invert_move;
  protobuf_c_boolean gamepad_invert_strafe;
  protobuf_c_boolean enable_vibration;
  protobuf_c_boolean invert_mouse_pitch;
  protobuf_c_boolean enable_mouse_smoothing;
  float mouse_scale;
  protobuf_c_boolean show_damage_numbers;
  protobuf_c_boolean show_damage_number_icons;
  protobuf_c_boolean enable_training_messages;
  protobuf_c_boolean show_text_chat;
  protobuf_c_boolean center_crosshair;
  protobuf_c_boolean toggle_sprint;
  protobuf_c_boolean toggle_crouch;
  protobuf_c_boolean censor_content;
  float music_volume;
  float sound_effects_volume;
  float vo_volume;
  float voice_volume;
  protobuf_c_boolean enable_optional_vo;
  protobuf_c_boolean push_to_talk;
  protobuf_c_boolean enable_controller_audio;
  float speaker_angle_front;
  float speaker_angle_side;
  float speaker_angle_back;
  uint32_t speaker_setup;
  protobuf_c_boolean mute_audio_on_focus_loss;
  protobuf_c_boolean hide_strict_nat_help_dialog;
  OakSave__PlayerInputBindings *player_input_bindings;
  size_t n_news_hashes;
  uint32_t *news_hashes;
  uint32_t last_used_savegame_id;
  int32_t gamepad_hip_sensitivity_level;
  int32_t gamepad_zoomed_sensitivity_level;
  int32_t gamepad_vehicle_sensitivity_level;
  float gamepad_movement_dead_zone_x;
  float gamepad_movement_dead_zone_y;
  float gamepad_look_dead_zone_inner_x;
  float gamepad_look_dead_zone_outer_x;
  float gamepad_look_dead_zone_inner_y;
  float gamepad_look_dead_zone_outer_y;
  float gamepad_vehicle_movement_dead_zone_x;
  float gamepad_vehicle_movement_dead_zone_y;
  float gamepad_vehicle_look_dead_zone_inner_x;
  float gamepad_vehicle_look_dead_zone_outer_x;
  float gamepad_vehicle_look_dead_zone_inner_y;
  float gamepad_vehicle_look_dead_zone_outer_y;
  float gamepad_left_dead_zone_inner;
  float gamepad_left_dead_zone_outer;
  float gamepad_right_dead_zone_inner;
  float gamepad_right_dead_zone_outer;
  float gamepad_look_axial_dead_zone_scale;
  float gamepad_move_axial_dead_zone_scale;
  protobuf_c_boolean gamepad_use_advanced_hip_aim_settings;
  protobuf_c_boolean gamepad_use_advanced_zoomed_aim_settings;
  protobuf_c_boolean gamepad_use_advanced_vehicle_aim_settings;
  float gamepad_hip_yaw_rate;
  float gamepad_hip_pitch_rate;
  float gamepad_hip_extra_yaw;
  float gamepad_hip_extra_pitch;
  float gamepad_hip_ramp_up_time;
  float gamepad_hip_ramp_up_delay;
  float gamepad_zoomed_yaw_rate;
  float gamepad_zoomed_pitch_rate;
  float gamepad_zoomed_extra_yaw;
  float gamepad_zoomed_extra_pitch;
  float gamepad_zoomed_ramp_up_time;
  float gamepad_zoomed_ramp_up_delay;
  float gamepad_vehicle_yaw_rate;
  float gamepad_vehicle_pitch_rate;
  float gamepad_vehicle_extra_yaw;
  float gamepad_vehicle_extra_pitch;
  float gamepad_vehicle_ramp_up_time;
  float gamepad_vehicle_ramp_up_delay;
  protobuf_c_boolean ironsight_aim_assist;
  uint32_t walking_joystick_scheme;
  uint32_t driving_joystick_scheme;
  float mouse_ads_scale;
  float mouse_vehicle_scale;
  protobuf_c_boolean mouse_ironsight_aim_assist;
  uint32_t vehicle_input_mode;
  protobuf_c_boolean weapon_aim_toggle;
  protobuf_c_boolean mantle_requires_button;
  protobuf_c_boolean fixed_minimap_rotation;
  protobuf_c_boolean map_invert_pitch;
  protobuf_c_boolean map_invert_yaw;
  uint32_t difficulty;
  protobuf_c_boolean swap_dual_wield_controls;
  float base_fov;
  uint32_t crosshair_neutral_color_frame;
  uint32_t crosshair_enemy_color_frame;
  uint32_t crosshair_ally_color_frame;
  protobuf_c_boolean enable_subtitles;
  protobuf_c_boolean enable_closed_captions;
  char *last_status_menu_page;
  size_t n_inventory_screen_last_filter;
  OakSave__OakProfileLastInventoryFilterInfo **inventory_screen_last_filter;
  OakSave__OakProfileMenuTutorialInfo *tutorial_info;
  uint32_t default_network_type;
  uint32_t default_invite_type;
  char *matchmaking_region;
  uint32_t streaming_service;
  int32_t max_cached_friend_events;
  int32_t max_cached_friend_statuses;
  size_t n_friend_events;
  char **friend_events;
  size_t n_friend_statuses;
  char **friend_statuses;
  int64_t last_whisper_fetch_events_time;
  int64_t last_whisper_fetch_statuses_time;
  uint32_t desired_crossplay_state;
  size_t n_friend_encounters;
  OakSave__Profile__FriendEncountersEntry **friend_encounters;
  int32_t max_friend_encounter_size;
  size_t n_profile_stats_data;
  OakSave__GameStatSaveGameData **profile_stats_data;
  size_t n_bank_inventory_category_list;
  OakSave__InventoryCategorySaveData **bank_inventory_category_list;
  size_t n_bank_inventory_list;
  ProtobufCBinaryData *bank_inventory_list;
  size_t n_lost_loot_inventory_list;
  ProtobufCBinaryData *lost_loot_inventory_list;
  size_t n_npc_mail_items;
  OakSave__OakMailItem **npc_mail_items;
  size_t n_mail_guids;
  char **mail_guids;
  size_t n_unread_mail_guids;
  char **unread_mail_guids;
  size_t n_gear_sold_by_friends;
  OakSave__GearSoldByFriendData **gear_sold_by_friends;
  size_t n_profile_sdu_list;
  OakSave__OakSDUSaveGameData **profile_sdu_list;
  size_t n_unlocked_customizations;
  OakSave__OakCustomizationSaveGameData **unlocked_customizations;
  size_t n_unlocked_inventory_customization_parts;
  OakSave__OakInventoryCustomizationPartInfo **unlocked_inventory_customization_parts;
  OakSave__GuardianRankProfileData *guardian_rank;
  size_t n_unlocked_crew_quarters_decorations;
  OakSave__CrewQuartersDecorationItemSaveGameData **unlocked_crew_quarters_decorations;
  size_t n_unlocked_crew_quarters_rooms;
  OakSave__CrewQuartersRoomItemSaveGameData **unlocked_crew_quarters_rooms;
  protobuf_c_boolean enable_mouse_acceleration;
  protobuf_c_boolean enable_gamepad_input;
  protobuf_c_boolean use_classic_gamepad_input;
  float master_volume;
  uint32_t monitor_display_type;
  uint32_t graphics_mode;
  uint32_t frame_rate_limit;
  float base_vehicle_fov;
  uint32_t graphics_quality;
  uint32_t anisotropic_filtering;
  uint32_t shadow_quality;
  uint32_t display_performance_stats;
  uint32_t texture_detail;
  uint32_t draw_distance;
  uint32_t clutter;
  uint32_t tessellation;
  uint32_t foliage;
  protobuf_c_boolean foliage_shadows;
  protobuf_c_boolean planar_reflections;
  uint32_t volumetric_fog;
  uint32_t screen_space_reflections;
  uint32_t character_texture_detail;
  uint32_t character_detail;
  uint32_t ambient_occlusion_quality;
  protobuf_c_boolean object_motion_blur;
  protobuf_c_boolean lens_flare;
  protobuf_c_boolean combat_number_long_format;
  protobuf_c_boolean show_minimap_legendaries;
  protobuf_c_boolean use_player_callouts;
  uint32_t friend_event_notification_lifetime;
  uint32_t friend_event_notification_frequency;
  uint32_t trade_request_reception_type;
  float head_bob_scale;
  protobuf_c_boolean has_seen_first_boot;
  float subs_cc_size;
  float cc_subs_background_opacity;
  uint32_t walking_button_scheme;
  uint32_t driving_button_scheme;
  uint32_t glyph_mode;
  protobuf_c_boolean use_mph;
  size_t n_registered_downloadable_entitlements;
  OakSave__RegisteredDownloadableEntitlements **registered_downloadable_entitlements;
  size_t n_seen_news_items;
  char **seen_news_items;
  protobuf_c_boolean auto_centering_enabled;
  protobuf_c_boolean increased_chance_for_subscribers;
  protobuf_c_boolean rare_chest_event_enabled;
  protobuf_c_boolean badass_event_enabled;
  protobuf_c_boolean pinata_event_enabled;
  int32_t min_time_between_badass_events;
  float hud_scale_multiplier;
  protobuf_c_boolean disable_spatial_audio;
  int32_t total_playtime_seconds;
  protobuf_c_boolean moxxis_drink_event_enabled;
  int32_t moxxis_drink_event_bits_product_id;
  size_t n_challenge_data;
  OakSave__ChallengeSaveGameData **challenge_data;
  size_t n_citizensciencelevelprogression;
  int32_t *citizensciencelevelprogression;
  protobuf_c_boolean default_dead_zone_inner_updated;
  protobuf_c_boolean disable_event_content;
  uint32_t desired_friend_sync_state;
  protobuf_c_boolean needs_shift_first_boot;
  size_t n_recently_met_players;
  OakSave__RecentlyMetPlayer **recently_met_players;
  int32_t citizenscienceactiveboosterindex;
  float citizenscienceactiveboosterremainingtime;
  float citizenscienceactiveboostertotaltime;
  int32_t streamerprimaryactiveboosterindex;
  float streamerprimaryactiveboosterremainingtime;
  float streamerprimaryactiveboostertotaltime;
  int32_t streamersecondaryactiveboosterindex;
  float streamersecondaryactiveboosterremainingtime;
  float streamersecondaryactiveboostertotaltime;
  int32_t streamerboostertier;
  int32_t citizensciencecsbucksamount;
  protobuf_c_boolean bcitizensciencehasseenintrovideo;
  protobuf_c_boolean bcitizensciencetutorialdone;
};
#define OAK_SAVE__PROFILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__profile__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0,NULL, NULL, 0, 0, (char *)protobuf_c_empty_string, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0,NULL, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0, 0, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* OakSave__PlayerInputBindingButton methods */
void   oak_save__player_input_binding__button__init
                     (OakSave__PlayerInputBindingButton         *message);
size_t oak_save__player_input_binding__button__get_packed_size
                     (const OakSave__PlayerInputBindingButton   *message);
size_t oak_save__player_input_binding__button__pack
                     (const OakSave__PlayerInputBindingButton   *message,
                      uint8_t             *out);
size_t oak_save__player_input_binding__button__pack_to_buffer
                     (const OakSave__PlayerInputBindingButton   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlayerInputBindingButton *
       oak_save__player_input_binding__button__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__player_input_binding__button__free_unpacked
                     (OakSave__PlayerInputBindingButton *message,
                      ProtobufCAllocator *allocator);
/* OakSave__PlayerInputBindingAxisKey methods */
void   oak_save__player_input_binding__axis__key__init
                     (OakSave__PlayerInputBindingAxisKey         *message);
size_t oak_save__player_input_binding__axis__key__get_packed_size
                     (const OakSave__PlayerInputBindingAxisKey   *message);
size_t oak_save__player_input_binding__axis__key__pack
                     (const OakSave__PlayerInputBindingAxisKey   *message,
                      uint8_t             *out);
size_t oak_save__player_input_binding__axis__key__pack_to_buffer
                     (const OakSave__PlayerInputBindingAxisKey   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlayerInputBindingAxisKey *
       oak_save__player_input_binding__axis__key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__player_input_binding__axis__key__free_unpacked
                     (OakSave__PlayerInputBindingAxisKey *message,
                      ProtobufCAllocator *allocator);
/* OakSave__PlayerInputBindingAxis methods */
void   oak_save__player_input_binding__axis__init
                     (OakSave__PlayerInputBindingAxis         *message);
size_t oak_save__player_input_binding__axis__get_packed_size
                     (const OakSave__PlayerInputBindingAxis   *message);
size_t oak_save__player_input_binding__axis__pack
                     (const OakSave__PlayerInputBindingAxis   *message,
                      uint8_t             *out);
size_t oak_save__player_input_binding__axis__pack_to_buffer
                     (const OakSave__PlayerInputBindingAxis   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlayerInputBindingAxis *
       oak_save__player_input_binding__axis__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__player_input_binding__axis__free_unpacked
                     (OakSave__PlayerInputBindingAxis *message,
                      ProtobufCAllocator *allocator);
/* OakSave__PlayerInputBindingCategory methods */
void   oak_save__player_input_binding__category__init
                     (OakSave__PlayerInputBindingCategory         *message);
size_t oak_save__player_input_binding__category__get_packed_size
                     (const OakSave__PlayerInputBindingCategory   *message);
size_t oak_save__player_input_binding__category__pack
                     (const OakSave__PlayerInputBindingCategory   *message,
                      uint8_t             *out);
size_t oak_save__player_input_binding__category__pack_to_buffer
                     (const OakSave__PlayerInputBindingCategory   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlayerInputBindingCategory *
       oak_save__player_input_binding__category__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__player_input_binding__category__free_unpacked
                     (OakSave__PlayerInputBindingCategory *message,
                      ProtobufCAllocator *allocator);
/* OakSave__PlayerInputBindings methods */
void   oak_save__player_input_bindings__init
                     (OakSave__PlayerInputBindings         *message);
size_t oak_save__player_input_bindings__get_packed_size
                     (const OakSave__PlayerInputBindings   *message);
size_t oak_save__player_input_bindings__pack
                     (const OakSave__PlayerInputBindings   *message,
                      uint8_t             *out);
size_t oak_save__player_input_bindings__pack_to_buffer
                     (const OakSave__PlayerInputBindings   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlayerInputBindings *
       oak_save__player_input_bindings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__player_input_bindings__free_unpacked
                     (OakSave__PlayerInputBindings *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakProfileLastInventoryFilterInfo methods */
void   oak_save__oak_profile_last_inventory_filter_info__init
                     (OakSave__OakProfileLastInventoryFilterInfo         *message);
size_t oak_save__oak_profile_last_inventory_filter_info__get_packed_size
                     (const OakSave__OakProfileLastInventoryFilterInfo   *message);
size_t oak_save__oak_profile_last_inventory_filter_info__pack
                     (const OakSave__OakProfileLastInventoryFilterInfo   *message,
                      uint8_t             *out);
size_t oak_save__oak_profile_last_inventory_filter_info__pack_to_buffer
                     (const OakSave__OakProfileLastInventoryFilterInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakProfileLastInventoryFilterInfo *
       oak_save__oak_profile_last_inventory_filter_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_profile_last_inventory_filter_info__free_unpacked
                     (OakSave__OakProfileLastInventoryFilterInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakProfileMenuTutorialInfo methods */
void   oak_save__oak_profile_menu_tutorial_info__init
                     (OakSave__OakProfileMenuTutorialInfo         *message);
size_t oak_save__oak_profile_menu_tutorial_info__get_packed_size
                     (const OakSave__OakProfileMenuTutorialInfo   *message);
size_t oak_save__oak_profile_menu_tutorial_info__pack
                     (const OakSave__OakProfileMenuTutorialInfo   *message,
                      uint8_t             *out);
size_t oak_save__oak_profile_menu_tutorial_info__pack_to_buffer
                     (const OakSave__OakProfileMenuTutorialInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakProfileMenuTutorialInfo *
       oak_save__oak_profile_menu_tutorial_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_profile_menu_tutorial_info__free_unpacked
                     (OakSave__OakProfileMenuTutorialInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakFriendEncounterData methods */
void   oak_save__oak_friend_encounter_data__init
                     (OakSave__OakFriendEncounterData         *message);
size_t oak_save__oak_friend_encounter_data__get_packed_size
                     (const OakSave__OakFriendEncounterData   *message);
size_t oak_save__oak_friend_encounter_data__pack
                     (const OakSave__OakFriendEncounterData   *message,
                      uint8_t             *out);
size_t oak_save__oak_friend_encounter_data__pack_to_buffer
                     (const OakSave__OakFriendEncounterData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakFriendEncounterData *
       oak_save__oak_friend_encounter_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_friend_encounter_data__free_unpacked
                     (OakSave__OakFriendEncounterData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakMailItem methods */
void   oak_save__oak_mail_item__init
                     (OakSave__OakMailItem         *message);
size_t oak_save__oak_mail_item__get_packed_size
                     (const OakSave__OakMailItem   *message);
size_t oak_save__oak_mail_item__pack
                     (const OakSave__OakMailItem   *message,
                      uint8_t             *out);
size_t oak_save__oak_mail_item__pack_to_buffer
                     (const OakSave__OakMailItem   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakMailItem *
       oak_save__oak_mail_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_mail_item__free_unpacked
                     (OakSave__OakMailItem *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GearSoldByFriendData methods */
void   oak_save__gear_sold_by_friend_data__init
                     (OakSave__GearSoldByFriendData         *message);
size_t oak_save__gear_sold_by_friend_data__get_packed_size
                     (const OakSave__GearSoldByFriendData   *message);
size_t oak_save__gear_sold_by_friend_data__pack
                     (const OakSave__GearSoldByFriendData   *message,
                      uint8_t             *out);
size_t oak_save__gear_sold_by_friend_data__pack_to_buffer
                     (const OakSave__GearSoldByFriendData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GearSoldByFriendData *
       oak_save__gear_sold_by_friend_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__gear_sold_by_friend_data__free_unpacked
                     (OakSave__GearSoldByFriendData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakCustomizationSaveGameData methods */
void   oak_save__oak_customization_save_game_data__init
                     (OakSave__OakCustomizationSaveGameData         *message);
size_t oak_save__oak_customization_save_game_data__get_packed_size
                     (const OakSave__OakCustomizationSaveGameData   *message);
size_t oak_save__oak_customization_save_game_data__pack
                     (const OakSave__OakCustomizationSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_customization_save_game_data__pack_to_buffer
                     (const OakSave__OakCustomizationSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakCustomizationSaveGameData *
       oak_save__oak_customization_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_customization_save_game_data__free_unpacked
                     (OakSave__OakCustomizationSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakInventoryCustomizationPartInfo methods */
void   oak_save__oak_inventory_customization_part_info__init
                     (OakSave__OakInventoryCustomizationPartInfo         *message);
size_t oak_save__oak_inventory_customization_part_info__get_packed_size
                     (const OakSave__OakInventoryCustomizationPartInfo   *message);
size_t oak_save__oak_inventory_customization_part_info__pack
                     (const OakSave__OakInventoryCustomizationPartInfo   *message,
                      uint8_t             *out);
size_t oak_save__oak_inventory_customization_part_info__pack_to_buffer
                     (const OakSave__OakInventoryCustomizationPartInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakInventoryCustomizationPartInfo *
       oak_save__oak_inventory_customization_part_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_inventory_customization_part_info__free_unpacked
                     (OakSave__OakInventoryCustomizationPartInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GuardianRankRewardSaveGameData methods */
void   oak_save__guardian_rank_reward_save_game_data__init
                     (OakSave__GuardianRankRewardSaveGameData         *message);
size_t oak_save__guardian_rank_reward_save_game_data__get_packed_size
                     (const OakSave__GuardianRankRewardSaveGameData   *message);
size_t oak_save__guardian_rank_reward_save_game_data__pack
                     (const OakSave__GuardianRankRewardSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__guardian_rank_reward_save_game_data__pack_to_buffer
                     (const OakSave__GuardianRankRewardSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GuardianRankRewardSaveGameData *
       oak_save__guardian_rank_reward_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__guardian_rank_reward_save_game_data__free_unpacked
                     (OakSave__GuardianRankRewardSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GuardianRankProfileData methods */
void   oak_save__guardian_rank_profile_data__init
                     (OakSave__GuardianRankProfileData         *message);
size_t oak_save__guardian_rank_profile_data__get_packed_size
                     (const OakSave__GuardianRankProfileData   *message);
size_t oak_save__guardian_rank_profile_data__pack
                     (const OakSave__GuardianRankProfileData   *message,
                      uint8_t             *out);
size_t oak_save__guardian_rank_profile_data__pack_to_buffer
                     (const OakSave__GuardianRankProfileData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GuardianRankProfileData *
       oak_save__guardian_rank_profile_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__guardian_rank_profile_data__free_unpacked
                     (OakSave__GuardianRankProfileData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CrewQuartersDecorationItemSaveGameData methods */
void   oak_save__crew_quarters_decoration_item_save_game_data__init
                     (OakSave__CrewQuartersDecorationItemSaveGameData         *message);
size_t oak_save__crew_quarters_decoration_item_save_game_data__get_packed_size
                     (const OakSave__CrewQuartersDecorationItemSaveGameData   *message);
size_t oak_save__crew_quarters_decoration_item_save_game_data__pack
                     (const OakSave__CrewQuartersDecorationItemSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__crew_quarters_decoration_item_save_game_data__pack_to_buffer
                     (const OakSave__CrewQuartersDecorationItemSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CrewQuartersDecorationItemSaveGameData *
       oak_save__crew_quarters_decoration_item_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__crew_quarters_decoration_item_save_game_data__free_unpacked
                     (OakSave__CrewQuartersDecorationItemSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CrewQuartersRoomItemSaveGameData methods */
void   oak_save__crew_quarters_room_item_save_game_data__init
                     (OakSave__CrewQuartersRoomItemSaveGameData         *message);
size_t oak_save__crew_quarters_room_item_save_game_data__get_packed_size
                     (const OakSave__CrewQuartersRoomItemSaveGameData   *message);
size_t oak_save__crew_quarters_room_item_save_game_data__pack
                     (const OakSave__CrewQuartersRoomItemSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__crew_quarters_room_item_save_game_data__pack_to_buffer
                     (const OakSave__CrewQuartersRoomItemSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CrewQuartersRoomItemSaveGameData *
       oak_save__crew_quarters_room_item_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__crew_quarters_room_item_save_game_data__free_unpacked
                     (OakSave__CrewQuartersRoomItemSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__RecentlyMetPlayer methods */
void   oak_save__recently_met_player__init
                     (OakSave__RecentlyMetPlayer         *message);
size_t oak_save__recently_met_player__get_packed_size
                     (const OakSave__RecentlyMetPlayer   *message);
size_t oak_save__recently_met_player__pack
                     (const OakSave__RecentlyMetPlayer   *message,
                      uint8_t             *out);
size_t oak_save__recently_met_player__pack_to_buffer
                     (const OakSave__RecentlyMetPlayer   *message,
                      ProtobufCBuffer     *buffer);
OakSave__RecentlyMetPlayer *
       oak_save__recently_met_player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__recently_met_player__free_unpacked
                     (OakSave__RecentlyMetPlayer *message,
                      ProtobufCAllocator *allocator);
/* OakSave__Profile__FriendEncountersEntry methods */
void   oak_save__profile__friend_encounters_entry__init
                     (OakSave__Profile__FriendEncountersEntry         *message);
/* OakSave__Profile methods */
void   oak_save__profile__init
                     (OakSave__Profile         *message);
size_t oak_save__profile__get_packed_size
                     (const OakSave__Profile   *message);
size_t oak_save__profile__pack
                     (const OakSave__Profile   *message,
                      uint8_t             *out);
size_t oak_save__profile__pack_to_buffer
                     (const OakSave__Profile   *message,
                      ProtobufCBuffer     *buffer);
OakSave__Profile *
       oak_save__profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__profile__free_unpacked
                     (OakSave__Profile *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*OakSave__PlayerInputBindingButton_Closure)
                 (const OakSave__PlayerInputBindingButton *message,
                  void *closure_data);
typedef void (*OakSave__PlayerInputBindingAxisKey_Closure)
                 (const OakSave__PlayerInputBindingAxisKey *message,
                  void *closure_data);
typedef void (*OakSave__PlayerInputBindingAxis_Closure)
                 (const OakSave__PlayerInputBindingAxis *message,
                  void *closure_data);
typedef void (*OakSave__PlayerInputBindingCategory_Closure)
                 (const OakSave__PlayerInputBindingCategory *message,
                  void *closure_data);
typedef void (*OakSave__PlayerInputBindings_Closure)
                 (const OakSave__PlayerInputBindings *message,
                  void *closure_data);
typedef void (*OakSave__OakProfileLastInventoryFilterInfo_Closure)
                 (const OakSave__OakProfileLastInventoryFilterInfo *message,
                  void *closure_data);
typedef void (*OakSave__OakProfileMenuTutorialInfo_Closure)
                 (const OakSave__OakProfileMenuTutorialInfo *message,
                  void *closure_data);
typedef void (*OakSave__OakFriendEncounterData_Closure)
                 (const OakSave__OakFriendEncounterData *message,
                  void *closure_data);
typedef void (*OakSave__OakMailItem_Closure)
                 (const OakSave__OakMailItem *message,
                  void *closure_data);
typedef void (*OakSave__GearSoldByFriendData_Closure)
                 (const OakSave__GearSoldByFriendData *message,
                  void *closure_data);
typedef void (*OakSave__OakCustomizationSaveGameData_Closure)
                 (const OakSave__OakCustomizationSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakInventoryCustomizationPartInfo_Closure)
                 (const OakSave__OakInventoryCustomizationPartInfo *message,
                  void *closure_data);
typedef void (*OakSave__GuardianRankRewardSaveGameData_Closure)
                 (const OakSave__GuardianRankRewardSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__GuardianRankProfileData_Closure)
                 (const OakSave__GuardianRankProfileData *message,
                  void *closure_data);
typedef void (*OakSave__CrewQuartersDecorationItemSaveGameData_Closure)
                 (const OakSave__CrewQuartersDecorationItemSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__CrewQuartersRoomItemSaveGameData_Closure)
                 (const OakSave__CrewQuartersRoomItemSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__RecentlyMetPlayer_Closure)
                 (const OakSave__RecentlyMetPlayer *message,
                  void *closure_data);
typedef void (*OakSave__Profile__FriendEncountersEntry_Closure)
                 (const OakSave__Profile__FriendEncountersEntry *message,
                  void *closure_data);
typedef void (*OakSave__Profile_Closure)
                 (const OakSave__Profile *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor oak_save__player_input_binding__button__descriptor;
extern const ProtobufCMessageDescriptor oak_save__player_input_binding__axis__key__descriptor;
extern const ProtobufCMessageDescriptor oak_save__player_input_binding__axis__descriptor;
extern const ProtobufCMessageDescriptor oak_save__player_input_binding__category__descriptor;
extern const ProtobufCMessageDescriptor oak_save__player_input_bindings__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_profile_last_inventory_filter_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_profile_menu_tutorial_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_friend_encounter_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_mail_item__descriptor;
extern const ProtobufCMessageDescriptor oak_save__gear_sold_by_friend_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_customization_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_inventory_customization_part_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__guardian_rank_reward_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__guardian_rank_profile_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__crew_quarters_decoration_item_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__crew_quarters_room_item_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__recently_met_player__descriptor;
extern const ProtobufCMessageDescriptor oak_save__profile__descriptor;
extern const ProtobufCMessageDescriptor oak_save__profile__friend_encounters_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_OakProfile_2eproto__INCLUDED */
