/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: OakShared.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "OakShared.pb-c.h"
void   oak_save__vec3__init
                     (OakSave__Vec3         *message)
{
  static const OakSave__Vec3 init_value = OAK_SAVE__VEC3__INIT;
  *message = init_value;
}
size_t oak_save__vec3__get_packed_size
                     (const OakSave__Vec3 *message)
{
  assert(message->base.descriptor == &oak_save__vec3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__vec3__pack
                     (const OakSave__Vec3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__vec3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__vec3__pack_to_buffer
                     (const OakSave__Vec3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__vec3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__Vec3 *
       oak_save__vec3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__Vec3 *)
     protobuf_c_message_unpack (&oak_save__vec3__descriptor,
                                allocator, len, data);
}
void   oak_save__vec3__free_unpacked
                     (OakSave__Vec3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__vec3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__game_stat_save_game_data__init
                     (OakSave__GameStatSaveGameData         *message)
{
  static const OakSave__GameStatSaveGameData init_value = OAK_SAVE__GAME_STAT_SAVE_GAME_DATA__INIT;
  *message = init_value;
}
size_t oak_save__game_stat_save_game_data__get_packed_size
                     (const OakSave__GameStatSaveGameData *message)
{
  assert(message->base.descriptor == &oak_save__game_stat_save_game_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__game_stat_save_game_data__pack
                     (const OakSave__GameStatSaveGameData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__game_stat_save_game_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__game_stat_save_game_data__pack_to_buffer
                     (const OakSave__GameStatSaveGameData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__game_stat_save_game_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__GameStatSaveGameData *
       oak_save__game_stat_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__GameStatSaveGameData *)
     protobuf_c_message_unpack (&oak_save__game_stat_save_game_data__descriptor,
                                allocator, len, data);
}
void   oak_save__game_stat_save_game_data__free_unpacked
                     (OakSave__GameStatSaveGameData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__game_stat_save_game_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__inventory_category_save_data__init
                     (OakSave__InventoryCategorySaveData         *message)
{
  static const OakSave__InventoryCategorySaveData init_value = OAK_SAVE__INVENTORY_CATEGORY_SAVE_DATA__INIT;
  *message = init_value;
}
size_t oak_save__inventory_category_save_data__get_packed_size
                     (const OakSave__InventoryCategorySaveData *message)
{
  assert(message->base.descriptor == &oak_save__inventory_category_save_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__inventory_category_save_data__pack
                     (const OakSave__InventoryCategorySaveData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__inventory_category_save_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__inventory_category_save_data__pack_to_buffer
                     (const OakSave__InventoryCategorySaveData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__inventory_category_save_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__InventoryCategorySaveData *
       oak_save__inventory_category_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__InventoryCategorySaveData *)
     protobuf_c_message_unpack (&oak_save__inventory_category_save_data__descriptor,
                                allocator, len, data);
}
void   oak_save__inventory_category_save_data__free_unpacked
                     (OakSave__InventoryCategorySaveData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__inventory_category_save_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__oak_sdusave_game_data__init
                     (OakSave__OakSDUSaveGameData         *message)
{
  static const OakSave__OakSDUSaveGameData init_value = OAK_SAVE__OAK_SDUSAVE_GAME_DATA__INIT;
  *message = init_value;
}
size_t oak_save__oak_sdusave_game_data__get_packed_size
                     (const OakSave__OakSDUSaveGameData *message)
{
  assert(message->base.descriptor == &oak_save__oak_sdusave_game_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__oak_sdusave_game_data__pack
                     (const OakSave__OakSDUSaveGameData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__oak_sdusave_game_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__oak_sdusave_game_data__pack_to_buffer
                     (const OakSave__OakSDUSaveGameData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__oak_sdusave_game_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__OakSDUSaveGameData *
       oak_save__oak_sdusave_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__OakSDUSaveGameData *)
     protobuf_c_message_unpack (&oak_save__oak_sdusave_game_data__descriptor,
                                allocator, len, data);
}
void   oak_save__oak_sdusave_game_data__free_unpacked
                     (OakSave__OakSDUSaveGameData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__oak_sdusave_game_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__registered_downloadable_entitlement__init
                     (OakSave__RegisteredDownloadableEntitlement         *message)
{
  static const OakSave__RegisteredDownloadableEntitlement init_value = OAK_SAVE__REGISTERED_DOWNLOADABLE_ENTITLEMENT__INIT;
  *message = init_value;
}
size_t oak_save__registered_downloadable_entitlement__get_packed_size
                     (const OakSave__RegisteredDownloadableEntitlement *message)
{
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__registered_downloadable_entitlement__pack
                     (const OakSave__RegisteredDownloadableEntitlement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__registered_downloadable_entitlement__pack_to_buffer
                     (const OakSave__RegisteredDownloadableEntitlement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__RegisteredDownloadableEntitlement *
       oak_save__registered_downloadable_entitlement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__RegisteredDownloadableEntitlement *)
     protobuf_c_message_unpack (&oak_save__registered_downloadable_entitlement__descriptor,
                                allocator, len, data);
}
void   oak_save__registered_downloadable_entitlement__free_unpacked
                     (OakSave__RegisteredDownloadableEntitlement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__registered_downloadable_entitlements__init
                     (OakSave__RegisteredDownloadableEntitlements         *message)
{
  static const OakSave__RegisteredDownloadableEntitlements init_value = OAK_SAVE__REGISTERED_DOWNLOADABLE_ENTITLEMENTS__INIT;
  *message = init_value;
}
size_t oak_save__registered_downloadable_entitlements__get_packed_size
                     (const OakSave__RegisteredDownloadableEntitlements *message)
{
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlements__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__registered_downloadable_entitlements__pack
                     (const OakSave__RegisteredDownloadableEntitlements *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlements__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__registered_downloadable_entitlements__pack_to_buffer
                     (const OakSave__RegisteredDownloadableEntitlements *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlements__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__RegisteredDownloadableEntitlements *
       oak_save__registered_downloadable_entitlements__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__RegisteredDownloadableEntitlements *)
     protobuf_c_message_unpack (&oak_save__registered_downloadable_entitlements__descriptor,
                                allocator, len, data);
}
void   oak_save__registered_downloadable_entitlements__free_unpacked
                     (OakSave__RegisteredDownloadableEntitlements *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__registered_downloadable_entitlements__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__challenge_stat_save_game_data__init
                     (OakSave__ChallengeStatSaveGameData         *message)
{
  static const OakSave__ChallengeStatSaveGameData init_value = OAK_SAVE__CHALLENGE_STAT_SAVE_GAME_DATA__INIT;
  *message = init_value;
}
size_t oak_save__challenge_stat_save_game_data__get_packed_size
                     (const OakSave__ChallengeStatSaveGameData *message)
{
  assert(message->base.descriptor == &oak_save__challenge_stat_save_game_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__challenge_stat_save_game_data__pack
                     (const OakSave__ChallengeStatSaveGameData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__challenge_stat_save_game_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__challenge_stat_save_game_data__pack_to_buffer
                     (const OakSave__ChallengeStatSaveGameData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__challenge_stat_save_game_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__ChallengeStatSaveGameData *
       oak_save__challenge_stat_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__ChallengeStatSaveGameData *)
     protobuf_c_message_unpack (&oak_save__challenge_stat_save_game_data__descriptor,
                                allocator, len, data);
}
void   oak_save__challenge_stat_save_game_data__free_unpacked
                     (OakSave__ChallengeStatSaveGameData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__challenge_stat_save_game_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__oak_challenge_reward_save_game_data__init
                     (OakSave__OakChallengeRewardSaveGameData         *message)
{
  static const OakSave__OakChallengeRewardSaveGameData init_value = OAK_SAVE__OAK_CHALLENGE_REWARD_SAVE_GAME_DATA__INIT;
  *message = init_value;
}
size_t oak_save__oak_challenge_reward_save_game_data__get_packed_size
                     (const OakSave__OakChallengeRewardSaveGameData *message)
{
  assert(message->base.descriptor == &oak_save__oak_challenge_reward_save_game_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__oak_challenge_reward_save_game_data__pack
                     (const OakSave__OakChallengeRewardSaveGameData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__oak_challenge_reward_save_game_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__oak_challenge_reward_save_game_data__pack_to_buffer
                     (const OakSave__OakChallengeRewardSaveGameData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__oak_challenge_reward_save_game_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__OakChallengeRewardSaveGameData *
       oak_save__oak_challenge_reward_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__OakChallengeRewardSaveGameData *)
     protobuf_c_message_unpack (&oak_save__oak_challenge_reward_save_game_data__descriptor,
                                allocator, len, data);
}
void   oak_save__oak_challenge_reward_save_game_data__free_unpacked
                     (OakSave__OakChallengeRewardSaveGameData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__oak_challenge_reward_save_game_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   oak_save__challenge_save_game_data__init
                     (OakSave__ChallengeSaveGameData         *message)
{
  static const OakSave__ChallengeSaveGameData init_value = OAK_SAVE__CHALLENGE_SAVE_GAME_DATA__INIT;
  *message = init_value;
}
size_t oak_save__challenge_save_game_data__get_packed_size
                     (const OakSave__ChallengeSaveGameData *message)
{
  assert(message->base.descriptor == &oak_save__challenge_save_game_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t oak_save__challenge_save_game_data__pack
                     (const OakSave__ChallengeSaveGameData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &oak_save__challenge_save_game_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t oak_save__challenge_save_game_data__pack_to_buffer
                     (const OakSave__ChallengeSaveGameData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &oak_save__challenge_save_game_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OakSave__ChallengeSaveGameData *
       oak_save__challenge_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OakSave__ChallengeSaveGameData *)
     protobuf_c_message_unpack (&oak_save__challenge_save_game_data__descriptor,
                                allocator, len, data);
}
void   oak_save__challenge_save_game_data__free_unpacked
                     (OakSave__ChallengeSaveGameData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &oak_save__challenge_save_game_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor oak_save__vec3__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(OakSave__Vec3, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(OakSave__Vec3, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(OakSave__Vec3, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__vec3__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange oak_save__vec3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor oak_save__vec3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.Vec3",
  "Vec3",
  "OakSave__Vec3",
  "OakSave",
  sizeof(OakSave__Vec3),
  3,
  oak_save__vec3__field_descriptors,
  oak_save__vec3__field_indices_by_name,
  1,  oak_save__vec3__number_ranges,
  (ProtobufCMessageInit) oak_save__vec3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__game_stat_save_game_data__field_descriptors[2] =
{
  {
    "stat_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__GameStatSaveGameData, stat_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stat_path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OakSave__GameStatSaveGameData, stat_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__game_stat_save_game_data__field_indices_by_name[] = {
  1,   /* field[1] = stat_path */
  0,   /* field[0] = stat_value */
};
static const ProtobufCIntRange oak_save__game_stat_save_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oak_save__game_stat_save_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.GameStatSaveGameData",
  "GameStatSaveGameData",
  "OakSave__GameStatSaveGameData",
  "OakSave",
  sizeof(OakSave__GameStatSaveGameData),
  2,
  oak_save__game_stat_save_game_data__field_descriptors,
  oak_save__game_stat_save_game_data__field_indices_by_name,
  1,  oak_save__game_stat_save_game_data__number_ranges,
  (ProtobufCMessageInit) oak_save__game_stat_save_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__inventory_category_save_data__field_descriptors[2] =
{
  {
    "base_category_definition_hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__InventoryCategorySaveData, base_category_definition_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quantity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__InventoryCategorySaveData, quantity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__inventory_category_save_data__field_indices_by_name[] = {
  0,   /* field[0] = base_category_definition_hash */
  1,   /* field[1] = quantity */
};
static const ProtobufCIntRange oak_save__inventory_category_save_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oak_save__inventory_category_save_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.InventoryCategorySaveData",
  "InventoryCategorySaveData",
  "OakSave__InventoryCategorySaveData",
  "OakSave",
  sizeof(OakSave__InventoryCategorySaveData),
  2,
  oak_save__inventory_category_save_data__field_descriptors,
  oak_save__inventory_category_save_data__field_indices_by_name,
  1,  oak_save__inventory_category_save_data__number_ranges,
  (ProtobufCMessageInit) oak_save__inventory_category_save_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__oak_sdusave_game_data__field_descriptors[2] =
{
  {
    "sdu_level",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__OakSDUSaveGameData, sdu_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdu_data_path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OakSave__OakSDUSaveGameData, sdu_data_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__oak_sdusave_game_data__field_indices_by_name[] = {
  1,   /* field[1] = sdu_data_path */
  0,   /* field[0] = sdu_level */
};
static const ProtobufCIntRange oak_save__oak_sdusave_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oak_save__oak_sdusave_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.OakSDUSaveGameData",
  "OakSDUSaveGameData",
  "OakSave__OakSDUSaveGameData",
  "OakSave",
  sizeof(OakSave__OakSDUSaveGameData),
  2,
  oak_save__oak_sdusave_game_data__field_descriptors,
  oak_save__oak_sdusave_game_data__field_indices_by_name,
  1,  oak_save__oak_sdusave_game_data__number_ranges,
  (ProtobufCMessageInit) oak_save__oak_sdusave_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__registered_downloadable_entitlement__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__RegisteredDownloadableEntitlement, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "consumed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__RegisteredDownloadableEntitlement, consumed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "registered",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OakSave__RegisteredDownloadableEntitlement, registered),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seen",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OakSave__RegisteredDownloadableEntitlement, seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__registered_downloadable_entitlement__field_indices_by_name[] = {
  1,   /* field[1] = consumed */
  0,   /* field[0] = id */
  2,   /* field[2] = registered */
  3,   /* field[3] = seen */
};
static const ProtobufCIntRange oak_save__registered_downloadable_entitlement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor oak_save__registered_downloadable_entitlement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.RegisteredDownloadableEntitlement",
  "RegisteredDownloadableEntitlement",
  "OakSave__RegisteredDownloadableEntitlement",
  "OakSave",
  sizeof(OakSave__RegisteredDownloadableEntitlement),
  4,
  oak_save__registered_downloadable_entitlement__field_descriptors,
  oak_save__registered_downloadable_entitlement__field_indices_by_name,
  1,  oak_save__registered_downloadable_entitlement__number_ranges,
  (ProtobufCMessageInit) oak_save__registered_downloadable_entitlement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__registered_downloadable_entitlements__field_descriptors[3] =
{
  {
    "entitlement_source_asset_path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OakSave__RegisteredDownloadableEntitlements, entitlement_source_asset_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entitlement_ids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(OakSave__RegisteredDownloadableEntitlements, n_entitlement_ids),
    offsetof(OakSave__RegisteredDownloadableEntitlements, entitlement_ids),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entitlements",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OakSave__RegisteredDownloadableEntitlements, n_entitlements),
    offsetof(OakSave__RegisteredDownloadableEntitlements, entitlements),
    &oak_save__registered_downloadable_entitlement__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__registered_downloadable_entitlements__field_indices_by_name[] = {
  1,   /* field[1] = entitlement_ids */
  0,   /* field[0] = entitlement_source_asset_path */
  2,   /* field[2] = entitlements */
};
static const ProtobufCIntRange oak_save__registered_downloadable_entitlements__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor oak_save__registered_downloadable_entitlements__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.RegisteredDownloadableEntitlements",
  "RegisteredDownloadableEntitlements",
  "OakSave__RegisteredDownloadableEntitlements",
  "OakSave",
  sizeof(OakSave__RegisteredDownloadableEntitlements),
  3,
  oak_save__registered_downloadable_entitlements__field_descriptors,
  oak_save__registered_downloadable_entitlements__field_indices_by_name,
  1,  oak_save__registered_downloadable_entitlements__number_ranges,
  (ProtobufCMessageInit) oak_save__registered_downloadable_entitlements__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__challenge_stat_save_game_data__field_descriptors[2] =
{
  {
    "current_stat_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeStatSaveGameData, current_stat_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge_stat_path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeStatSaveGameData, challenge_stat_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__challenge_stat_save_game_data__field_indices_by_name[] = {
  1,   /* field[1] = challenge_stat_path */
  0,   /* field[0] = current_stat_value */
};
static const ProtobufCIntRange oak_save__challenge_stat_save_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor oak_save__challenge_stat_save_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.ChallengeStatSaveGameData",
  "ChallengeStatSaveGameData",
  "OakSave__ChallengeStatSaveGameData",
  "OakSave",
  sizeof(OakSave__ChallengeStatSaveGameData),
  2,
  oak_save__challenge_stat_save_game_data__field_descriptors,
  oak_save__challenge_stat_save_game_data__field_indices_by_name,
  1,  oak_save__challenge_stat_save_game_data__number_ranges,
  (ProtobufCMessageInit) oak_save__challenge_stat_save_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__oak_challenge_reward_save_game_data__field_descriptors[1] =
{
  {
    "challenge_reward_claimed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OakSave__OakChallengeRewardSaveGameData, challenge_reward_claimed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__oak_challenge_reward_save_game_data__field_indices_by_name[] = {
  0,   /* field[0] = challenge_reward_claimed */
};
static const ProtobufCIntRange oak_save__oak_challenge_reward_save_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor oak_save__oak_challenge_reward_save_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.OakChallengeRewardSaveGameData",
  "OakChallengeRewardSaveGameData",
  "OakSave__OakChallengeRewardSaveGameData",
  "OakSave",
  sizeof(OakSave__OakChallengeRewardSaveGameData),
  1,
  oak_save__oak_challenge_reward_save_game_data__field_descriptors,
  oak_save__oak_challenge_reward_save_game_data__field_indices_by_name,
  1,  oak_save__oak_challenge_reward_save_game_data__number_ranges,
  (ProtobufCMessageInit) oak_save__oak_challenge_reward_save_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor oak_save__challenge_save_game_data__field_descriptors[8] =
{
  {
    "completed_count",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeSaveGameData, completed_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_active",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeSaveGameData, is_active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currently_completed",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeSaveGameData, currently_completed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "completed_progress_level",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeSaveGameData, completed_progress_level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "progress_counter",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeSaveGameData, progress_counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stat_instance_state",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OakSave__ChallengeSaveGameData, n_stat_instance_state),
    offsetof(OakSave__ChallengeSaveGameData, stat_instance_state),
    &oak_save__challenge_stat_save_game_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge_class_path",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OakSave__ChallengeSaveGameData, challenge_class_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge_reward_info",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OakSave__ChallengeSaveGameData, n_challenge_reward_info),
    offsetof(OakSave__ChallengeSaveGameData, challenge_reward_info),
    &oak_save__oak_challenge_reward_save_game_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned oak_save__challenge_save_game_data__field_indices_by_name[] = {
  6,   /* field[6] = challenge_class_path */
  7,   /* field[7] = challenge_reward_info */
  0,   /* field[0] = completed_count */
  3,   /* field[3] = completed_progress_level */
  2,   /* field[2] = currently_completed */
  1,   /* field[1] = is_active */
  4,   /* field[4] = progress_counter */
  5,   /* field[5] = stat_instance_state */
};
static const ProtobufCIntRange oak_save__challenge_save_game_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor oak_save__challenge_save_game_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OakSave.ChallengeSaveGameData",
  "ChallengeSaveGameData",
  "OakSave__ChallengeSaveGameData",
  "OakSave",
  sizeof(OakSave__ChallengeSaveGameData),
  8,
  oak_save__challenge_save_game_data__field_descriptors,
  oak_save__challenge_save_game_data__field_indices_by_name,
  1,  oak_save__challenge_save_game_data__number_ranges,
  (ProtobufCMessageInit) oak_save__challenge_save_game_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
