/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: OakSave.proto */

#ifndef PROTOBUF_C_OakSave_2eproto__INCLUDED
#define PROTOBUF_C_OakSave_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "OakShared.pb-c.h"

typedef struct _OakSave__PlayerClassSaveGameData OakSave__PlayerClassSaveGameData;
typedef struct _OakSave__ResourcePoolSavegameData OakSave__ResourcePoolSavegameData;
typedef struct _OakSave__RegionSaveGameData OakSave__RegionSaveGameData;
typedef struct _OakSave__InventoryBalanceStateInitializationData OakSave__InventoryBalanceStateInitializationData;
typedef struct _OakSave__OakInventoryItemSaveGameData OakSave__OakInventoryItemSaveGameData;
typedef struct _OakSave__EquippedInventorySaveGameData OakSave__EquippedInventorySaveGameData;
typedef struct _OakSave__OakAbilityTreeItemSaveGameData OakSave__OakAbilityTreeItemSaveGameData;
typedef struct _OakSave__OakAbilitySlotSaveGameData OakSave__OakAbilitySlotSaveGameData;
typedef struct _OakSave__OakActionAbilityAugmentSaveGameData OakSave__OakActionAbilityAugmentSaveGameData;
typedef struct _OakSave__OakActionAbilityAugmentConfigurationSaveGameData OakSave__OakActionAbilityAugmentConfigurationSaveGameData;
typedef struct _OakSave__OakPlayerAbilitySaveGameData OakSave__OakPlayerAbilitySaveGameData;
typedef struct _OakSave__MissionStatusPlayerSaveGameData OakSave__MissionStatusPlayerSaveGameData;
typedef struct _OakSave__MissionPlaythroughSaveGameData OakSave__MissionPlaythroughSaveGameData;
typedef struct _OakSave__ActiveFastTravelSaveData OakSave__ActiveFastTravelSaveData;
typedef struct _OakSave__PlaythroughActiveFastTravelSaveData OakSave__PlaythroughActiveFastTravelSaveData;
typedef struct _OakSave__DiscoveredAreaInfo OakSave__DiscoveredAreaInfo;
typedef struct _OakSave__DiscoveredLevelInfo OakSave__DiscoveredLevelInfo;
typedef struct _OakSave__DiscoveredPlanetInfo OakSave__DiscoveredPlanetInfo;
typedef struct _OakSave__DiscoverySaveData OakSave__DiscoverySaveData;
typedef struct _OakSave__VehicleUnlockedSaveGameData OakSave__VehicleUnlockedSaveGameData;
typedef struct _OakSave__OakCARMenuVehicleConfigSaveData OakSave__OakCARMenuVehicleConfigSaveData;
typedef struct _OakSave__CustomPlayerColorSaveGameData OakSave__CustomPlayerColorSaveGameData;
typedef struct _OakSave__GuardianRankSaveGameData OakSave__GuardianRankSaveGameData;
typedef struct _OakSave__GuardianRankRewardCharacterSaveGameData OakSave__GuardianRankRewardCharacterSaveGameData;
typedef struct _OakSave__GuardianRankPerkCharacterSaveGameData OakSave__GuardianRankPerkCharacterSaveGameData;
typedef struct _OakSave__GuardianRankCharacterSaveGameData OakSave__GuardianRankCharacterSaveGameData;
typedef struct _OakSave__CrewQuartersDecorationSaveData OakSave__CrewQuartersDecorationSaveData;
typedef struct _OakSave__CrewQuartersSaveData OakSave__CrewQuartersSaveData;
typedef struct _OakSave__CrewQuartersGunRackItemSaveData OakSave__CrewQuartersGunRackItemSaveData;
typedef struct _OakSave__CrewQuartersGunRackSaveData OakSave__CrewQuartersGunRackSaveData;
typedef struct _OakSave__EchoLogSaveGameData OakSave__EchoLogSaveGameData;
typedef struct _OakSave__MapIDData OakSave__MapIDData;
typedef struct _OakSave__GameStateSaveData OakSave__GameStateSaveData;
typedef struct _OakSave__ChallengeCategoryProgressSaveData OakSave__ChallengeCategoryProgressSaveData;
typedef struct _OakSave__OakPlayerCharacterAugmentSaveGameData OakSave__OakPlayerCharacterAugmentSaveGameData;
typedef struct _OakSave__OakPlayerCharacterSlotSaveGameData OakSave__OakPlayerCharacterSlotSaveGameData;
typedef struct _OakSave__UITrackingSaveGameData OakSave__UITrackingSaveGameData;
typedef struct _OakSave__PlanetCycleInfo OakSave__PlanetCycleInfo;
typedef struct _OakSave__TimeOfDaySaveGameData OakSave__TimeOfDaySaveGameData;
typedef struct _OakSave__LevelPersistenceActorSaveGameData OakSave__LevelPersistenceActorSaveGameData;
typedef struct _OakSave__LevelPersistenceLevelSaveGameData OakSave__LevelPersistenceLevelSaveGameData;
typedef struct _OakSave__GbxZoneMapFODSavedLevelData OakSave__GbxZoneMapFODSavedLevelData;
typedef struct _OakSave__GbxZoneMapFODSaveGameData OakSave__GbxZoneMapFODSaveGameData;
typedef struct _OakSave__Character OakSave__Character;
typedef struct _OakSave__Character__NicknameMappingsEntry OakSave__Character__NicknameMappingsEntry;
typedef struct _OakSave__Character__ActiveLeagueInstanceForEventEntry OakSave__Character__ActiveLeagueInstanceForEventEntry;


/* --- enums --- */

typedef enum _OakSave__MissionStatusPlayerSaveGameData__MissionState {
  OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE__MS_NotStarted = 0,
  OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE__MS_Active = 1,
  OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE__MS_Complete = 2,
  OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE__MS_Failed = 3,
  OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE__MS_Unknown = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE)
} OakSave__MissionStatusPlayerSaveGameData__MissionState;

/* --- messages --- */

struct  _OakSave__PlayerClassSaveGameData
{
  ProtobufCMessage base;
  char *player_class_path;
  uint32_t dlc_package_id;
};
#define OAK_SAVE__PLAYER_CLASS_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__player_class_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__ResourcePoolSavegameData
{
  ProtobufCMessage base;
  float amount;
  char *resource_path;
};
#define OAK_SAVE__RESOURCE_POOL_SAVEGAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__resource_pool_savegame_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__RegionSaveGameData
{
  ProtobufCMessage base;
  int32_t game_stage;
  int32_t play_through_idx;
  char *region_path;
  uint32_t dlc_package_id;
};
#define OAK_SAVE__REGION_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__region_save_game_data__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__InventoryBalanceStateInitializationData
{
  ProtobufCMessage base;
  int32_t game_stage;
  char *inventory_data;
  char *inventory_balance_data;
  char *manufacturer_data;
  size_t n_part_list;
  char **part_list;
  size_t n_generic_part_list;
  char **generic_part_list;
  ProtobufCBinaryData additional_data;
  size_t n_customization_part_list;
  char **customization_part_list;
};
#define OAK_SAVE__INVENTORY_BALANCE_STATE_INITIALIZATION_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__inventory_balance_state_initialization_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, {0,NULL}, 0,NULL }


struct  _OakSave__OakInventoryItemSaveGameData
{
  ProtobufCMessage base;
  ProtobufCBinaryData item_serial_number;
  int32_t pickup_order_index;
  int32_t flags;
  char *weapon_skin_path;
  OakSave__InventoryBalanceStateInitializationData *development_save_data;
};
#define OAK_SAVE__OAK_INVENTORY_ITEM_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_inventory_item_save_game_data__descriptor) \
    , {0,NULL}, 0, 0, (char *)protobuf_c_empty_string, NULL }


struct  _OakSave__EquippedInventorySaveGameData
{
  ProtobufCMessage base;
  int32_t inventory_list_index;
  protobuf_c_boolean enabled;
  char *slot_data_path;
  char *trinket_data_path;
};
#define OAK_SAVE__EQUIPPED_INVENTORY_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__equipped_inventory_save_game_data__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OakSave__OakAbilityTreeItemSaveGameData
{
  ProtobufCMessage base;
  char *item_asset_path;
  int32_t points;
  int32_t max_points;
  int32_t tree_identifier;
};
#define OAK_SAVE__OAK_ABILITY_TREE_ITEM_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_ability_tree_item_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  _OakSave__OakAbilitySlotSaveGameData
{
  ProtobufCMessage base;
  char *ability_class_path;
  char *slot_asset_path;
};
#define OAK_SAVE__OAK_ABILITY_SLOT_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_ability_slot_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OakSave__OakActionAbilityAugmentSaveGameData
{
  ProtobufCMessage base;
  char *action_ability_class_path;
  char *slot_asset_path;
  char *augment_asset_path;
};
#define OAK_SAVE__OAK_ACTION_ABILITY_AUGMENT_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_action_ability_augment_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OakSave__OakActionAbilityAugmentConfigurationSaveGameData
{
  ProtobufCMessage base;
  char *ability_class_path;
  char *augment_asset_path;
  char *mod_slot_asset_path;
  char *mod_asset_path;
};
#define OAK_SAVE__OAK_ACTION_ABILITY_AUGMENT_CONFIGURATION_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_action_ability_augment_configuration_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OakSave__OakPlayerAbilitySaveGameData
{
  ProtobufCMessage base;
  int32_t ability_points;
  size_t n_tree_item_list;
  OakSave__OakAbilityTreeItemSaveGameData **tree_item_list;
  size_t n_ability_slot_list;
  OakSave__OakAbilitySlotSaveGameData **ability_slot_list;
  size_t n_augment_slot_list;
  OakSave__OakActionAbilityAugmentSaveGameData **augment_slot_list;
  size_t n_augment_configuration_list;
  OakSave__OakActionAbilityAugmentConfigurationSaveGameData **augment_configuration_list;
  int32_t tree_grade;
};
#define OAK_SAVE__OAK_PLAYER_ABILITY_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_player_ability_save_game_data__descriptor) \
    , 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0 }


struct  _OakSave__MissionStatusPlayerSaveGameData
{
  ProtobufCMessage base;
  OakSave__MissionStatusPlayerSaveGameData__MissionState status;
  protobuf_c_boolean has_been_viewed_in_log;
  size_t n_objectives_progress;
  int32_t *objectives_progress;
  char *mission_class_path;
  char *active_objective_set_path;
  uint32_t dlc_package_id;
  protobuf_c_boolean kickoff_played;
  uint32_t league_instance;
};
#define OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__mission_status_player_save_game_data__descriptor) \
    , OAK_SAVE__MISSION_STATUS_PLAYER_SAVE_GAME_DATA__MISSION_STATE__MS_NotStarted, 0, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  _OakSave__MissionPlaythroughSaveGameData
{
  ProtobufCMessage base;
  size_t n_mission_list;
  OakSave__MissionStatusPlayerSaveGameData **mission_list;
  char *tracked_mission_class_path;
};
#define OAK_SAVE__MISSION_PLAYTHROUGH_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__mission_playthrough_save_game_data__descriptor) \
    , 0,NULL, (char *)protobuf_c_empty_string }


struct  _OakSave__ActiveFastTravelSaveData
{
  ProtobufCMessage base;
  char *active_travel_station_name;
  protobuf_c_boolean blacklisted;
};
#define OAK_SAVE__ACTIVE_FAST_TRAVEL_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__active_fast_travel_save_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__PlaythroughActiveFastTravelSaveData
{
  ProtobufCMessage base;
  size_t n_active_travel_stations;
  OakSave__ActiveFastTravelSaveData **active_travel_stations;
};
#define OAK_SAVE__PLAYTHROUGH_ACTIVE_FAST_TRAVEL_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__playthrough_active_fast_travel_save_data__descriptor) \
    , 0,NULL }


struct  _OakSave__DiscoveredAreaInfo
{
  ProtobufCMessage base;
  char *discovered_area_name;
  uint32_t discovered_playthroughs;
};
#define OAK_SAVE__DISCOVERED_AREA_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__discovered_area_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__DiscoveredLevelInfo
{
  ProtobufCMessage base;
  char *discovered_level_name;
  uint32_t discovered_playthroughs;
  size_t n_discovered_area_info;
  OakSave__DiscoveredAreaInfo **discovered_area_info;
};
#define OAK_SAVE__DISCOVERED_LEVEL_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__discovered_level_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0,NULL }


struct  _OakSave__DiscoveredPlanetInfo
{
  ProtobufCMessage base;
  char *discovered_planet;
  protobuf_c_boolean is_new_planet;
};
#define OAK_SAVE__DISCOVERED_PLANET_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__discovered_planet_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__DiscoverySaveData
{
  ProtobufCMessage base;
  size_t n_discovered_level_info;
  OakSave__DiscoveredLevelInfo **discovered_level_info;
};
#define OAK_SAVE__DISCOVERY_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__discovery_save_data__descriptor) \
    , 0,NULL }


struct  _OakSave__VehicleUnlockedSaveGameData
{
  ProtobufCMessage base;
  char *asset_path;
  protobuf_c_boolean just_unlocked;
};
#define OAK_SAVE__VEHICLE_UNLOCKED_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__vehicle_unlocked_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__OakCARMenuVehicleConfigSaveData
{
  ProtobufCMessage base;
  char *loadout_save_name;
  char *body_asset_path;
  char *wheel_asset_path;
  char *armor_asset_path;
  char *core_mod_asset_path;
  char *gunner_weapon_asset_path;
  char *driver_weapon_asset_path;
  char *ornament_asset_path;
  char *material_decal_asset_path;
  char *material_asset_path;
  int32_t color_index_1;
  int32_t color_index_2;
  int32_t color_index_3;
};
#define OAK_SAVE__OAK_CARMENU_VEHICLE_CONFIG_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_carmenu_vehicle_config_save_data__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  _OakSave__CustomPlayerColorSaveGameData
{
  ProtobufCMessage base;
  char *color_parameter;
  OakSave__Vec3 *applied_color;
  OakSave__Vec3 *split_color;
  protobuf_c_boolean use_default_color;
  protobuf_c_boolean use_default_split_color;
};
#define OAK_SAVE__CUSTOM_PLAYER_COLOR_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__custom_player_color_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, NULL, 0, 0 }


struct  _OakSave__GuardianRankSaveGameData
{
  ProtobufCMessage base;
  int32_t guardian_rank;
  int32_t guardian_experience;
};
#define OAK_SAVE__GUARDIAN_RANK_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__guardian_rank_save_game_data__descriptor) \
    , 0, 0 }


struct  _OakSave__GuardianRankRewardCharacterSaveGameData
{
  ProtobufCMessage base;
  int32_t num_tokens;
  protobuf_c_boolean is_enabled;
  char *reward_data_path;
};
#define OAK_SAVE__GUARDIAN_RANK_REWARD_CHARACTER_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__guardian_rank_reward_character_save_game_data__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string }


struct  _OakSave__GuardianRankPerkCharacterSaveGameData
{
  ProtobufCMessage base;
  protobuf_c_boolean is_enabled;
  char *perk_data_path;
};
#define OAK_SAVE__GUARDIAN_RANK_PERK_CHARACTER_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__guardian_rank_perk_character_save_game_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__GuardianRankCharacterSaveGameData
{
  ProtobufCMessage base;
  int32_t guardian_available_tokens;
  int32_t guardian_rank;
  int32_t guardian_experience;
  size_t n_rank_rewards;
  OakSave__GuardianRankRewardCharacterSaveGameData **rank_rewards;
  size_t n_rank_perks;
  OakSave__GuardianRankPerkCharacterSaveGameData **rank_perks;
  int32_t guardian_reward_random_seed;
  int64_t new_guardian_experience;
  protobuf_c_boolean is_rank_system_enabled;
};
#define OAK_SAVE__GUARDIAN_RANK_CHARACTER_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__guardian_rank_character_save_game_data__descriptor) \
    , 0, 0, 0, 0,NULL, 0,NULL, 0, 0, 0 }


struct  _OakSave__CrewQuartersDecorationSaveData
{
  ProtobufCMessage base;
  int32_t decoration_index;
  char *decoration_data_path;
};
#define OAK_SAVE__CREW_QUARTERS_DECORATION_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__crew_quarters_decoration_save_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__CrewQuartersSaveData
{
  ProtobufCMessage base;
  int32_t preferred_room_assignment;
  size_t n_decorations;
  OakSave__CrewQuartersDecorationSaveData **decorations;
  char *room_data_path;
};
#define OAK_SAVE__CREW_QUARTERS_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__crew_quarters_save_data__descriptor) \
    , 0, 0,NULL, (char *)protobuf_c_empty_string }


struct  _OakSave__CrewQuartersGunRackItemSaveData
{
  ProtobufCMessage base;
  ProtobufCBinaryData encrypted_serial_number;
  char *slot_asset_path;
  OakSave__InventoryBalanceStateInitializationData *development_save_data;
};
#define OAK_SAVE__CREW_QUARTERS_GUN_RACK_ITEM_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__crew_quarters_gun_rack_item_save_data__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, NULL }


struct  _OakSave__CrewQuartersGunRackSaveData
{
  ProtobufCMessage base;
  size_t n_rack_save_data;
  OakSave__CrewQuartersGunRackItemSaveData **rack_save_data;
};
#define OAK_SAVE__CREW_QUARTERS_GUN_RACK_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__crew_quarters_gun_rack_save_data__descriptor) \
    , 0,NULL }


struct  _OakSave__EchoLogSaveGameData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_been_seen_in_log;
  char *echo_log_path;
};
#define OAK_SAVE__ECHO_LOG_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__echo_log_save_game_data__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _OakSave__MapIDData
{
  ProtobufCMessage base;
  uint32_t zone_name_id;
  uint32_t map_name_id;
};
#define OAK_SAVE__MAP_IDDATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__map_iddata__descriptor) \
    , 0, 0 }


struct  _OakSave__GameStateSaveData
{
  ProtobufCMessage base;
  OakSave__MapIDData *last_traveled_map_id;
  int32_t mayhem_level;
  int32_t mayhem_random_seed;
};
#define OAK_SAVE__GAME_STATE_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__game_state_save_data__descriptor) \
    , NULL, 0, 0 }


struct  _OakSave__ChallengeCategoryProgressSaveData
{
  ProtobufCMessage base;
  ProtobufCBinaryData category_progress;
};
#define OAK_SAVE__CHALLENGE_CATEGORY_PROGRESS_SAVE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__challenge_category_progress_save_data__descriptor) \
    , {0,NULL} }


struct  _OakSave__OakPlayerCharacterAugmentSaveGameData
{
  ProtobufCMessage base;
  char *slot_asset_path;
  char *augment_asset_path;
};
#define OAK_SAVE__OAK_PLAYER_CHARACTER_AUGMENT_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_player_character_augment_save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OakSave__OakPlayerCharacterSlotSaveGameData
{
  ProtobufCMessage base;
  size_t n_augment_slot_list;
  OakSave__OakPlayerCharacterAugmentSaveGameData **augment_slot_list;
};
#define OAK_SAVE__OAK_PLAYER_CHARACTER_SLOT_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__oak_player_character_slot_save_game_data__descriptor) \
    , 0,NULL }


struct  _OakSave__UITrackingSaveGameData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_seen_skill_menu_unlock;
  protobuf_c_boolean has_seen_guardian_rank_menu_unlock;
  protobuf_c_boolean has_seen_echo_boot_ammo_bar;
  protobuf_c_boolean has_seen_echo_boot_shield_bar;
  protobuf_c_boolean has_seen_echo_boot_grenades;
  int32_t highest_thvm_breadcrumb_seen;
  size_t n_inventory_slot_unlocks_seen;
  char **inventory_slot_unlocks_seen;
  int32_t saved_spin_offset;
};
#define OAK_SAVE__UITRACKING_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__uitracking_save_game_data__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0,NULL, 0 }


struct  _OakSave__PlanetCycleInfo
{
  ProtobufCMessage base;
  char *planet_name;
  float cycle_length;
  float last_cached_time;
};
#define OAK_SAVE__PLANET_CYCLE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__planet_cycle_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


struct  _OakSave__TimeOfDaySaveGameData
{
  ProtobufCMessage base;
  size_t n_planet_cycle_info;
  OakSave__PlanetCycleInfo **planet_cycle_info;
  char *planet_cycle;
};
#define OAK_SAVE__TIME_OF_DAY_SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__time_of_day_save_game_data__descriptor) \
    , 0,NULL, (char *)protobuf_c_empty_string }


struct  _OakSave__LevelPersistenceActorSaveGameData
{
  ProtobufCMessage base;
  char *actor_name;
  int32_t timer_remaining;
};
#define OAK_SAVE__LEVEL_PERSISTENCE__ACTOR__SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__level_persistence__actor__save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _OakSave__LevelPersistenceLevelSaveGameData
{
  ProtobufCMessage base;
  char *level_name;
  size_t n_saved_actors;
  OakSave__LevelPersistenceActorSaveGameData **saved_actors;
};
#define OAK_SAVE__LEVEL_PERSISTENCE__LEVEL__SAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__level_persistence__level__save_game_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  _OakSave__GbxZoneMapFODSavedLevelData
{
  ProtobufCMessage base;
  char *level_name;
  uint32_t fod_texture_size;
  uint32_t num_chunks;
  float discovery_percentage;
  uint32_t data_state;
  uint32_t data_revision;
  ProtobufCBinaryData fod_data;
};
#define OAK_SAVE__GBX_ZONE_MAP_FODSAVED_LEVEL_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__gbx_zone_map_fodsaved_level_data__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, {0,NULL} }


struct  _OakSave__GbxZoneMapFODSaveGameData
{
  ProtobufCMessage base;
  size_t n_level_data;
  OakSave__GbxZoneMapFODSavedLevelData **level_data;
};
#define OAK_SAVE__GBX_ZONE_MAP_FODSAVE_GAME_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__gbx_zone_map_fodsave_game_data__descriptor) \
    , 0,NULL }


struct  _OakSave__Character__NicknameMappingsEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define OAK_SAVE__CHARACTER__NICKNAME_MAPPINGS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__character__nickname_mappings_entry__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _OakSave__Character__ActiveLeagueInstanceForEventEntry
{
  ProtobufCMessage base;
  uint32_t key;
  uint32_t value;
};
#define OAK_SAVE__CHARACTER__ACTIVE_LEAGUE_INSTANCE_FOR_EVENT_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__character__active_league_instance_for_event_entry__descriptor) \
    , 0, 0 }


struct  _OakSave__Character
{
  ProtobufCMessage base;
  uint32_t save_game_id;
  int64_t last_save_timestamp;
  uint32_t time_played_seconds;
  OakSave__PlayerClassSaveGameData *player_class_data;
  size_t n_resource_pools;
  OakSave__ResourcePoolSavegameData **resource_pools;
  size_t n_saved_regions;
  OakSave__RegionSaveGameData **saved_regions;
  int32_t experience_points;
  size_t n_game_stats_data;
  OakSave__GameStatSaveGameData **game_stats_data;
  size_t n_inventory_category_list;
  OakSave__InventoryCategorySaveData **inventory_category_list;
  size_t n_inventory_items;
  OakSave__OakInventoryItemSaveGameData **inventory_items;
  size_t n_equipped_inventory_list;
  OakSave__EquippedInventorySaveGameData **equipped_inventory_list;
  size_t n_active_weapon_list;
  int32_t *active_weapon_list;
  OakSave__OakPlayerAbilitySaveGameData *ability_data;
  int32_t last_play_through_index;
  int32_t playthroughs_completed;
  protobuf_c_boolean show_new_playthrough_notification;
  size_t n_mission_playthroughs_data;
  OakSave__MissionPlaythroughSaveGameData **mission_playthroughs_data;
  size_t n_active_travel_stations;
  char **active_travel_stations;
  OakSave__DiscoverySaveData *discovery_data;
  char *last_active_travel_station;
  size_t n_vehicles_unlocked_data;
  OakSave__VehicleUnlockedSaveGameData **vehicles_unlocked_data;
  size_t n_vehicle_parts_unlocked;
  char **vehicle_parts_unlocked;
  size_t n_vehicle_loadouts;
  OakSave__OakCARMenuVehicleConfigSaveData **vehicle_loadouts;
  int32_t vehicle_last_loadout_index;
  size_t n_challenge_data;
  OakSave__ChallengeSaveGameData **challenge_data;
  size_t n_sdu_list;
  OakSave__OakSDUSaveGameData **sdu_list;
  size_t n_selected_customizations;
  char **selected_customizations;
  size_t n_equipped_emote_customizations;
  int32_t *equipped_emote_customizations;
  size_t n_selected_color_customizations;
  OakSave__CustomPlayerColorSaveGameData **selected_color_customizations;
  OakSave__GuardianRankSaveGameData *guardian_rank;
  OakSave__CrewQuartersSaveData *crew_quarters_room;
  OakSave__CrewQuartersGunRackSaveData *crew_quarters_gun_rack;
  size_t n_unlocked_echo_logs;
  OakSave__EchoLogSaveGameData **unlocked_echo_logs;
  protobuf_c_boolean has_played_special_echo_log_insert_already;
  size_t n_nickname_mappings;
  OakSave__Character__NicknameMappingsEntry **nickname_mappings;
  OakSave__MapIDData *last_traveled_map_id;
  OakSave__ChallengeCategoryProgressSaveData *challenge_category_completion_pcts;
  OakSave__OakPlayerCharacterSlotSaveGameData *character_slot_save_game_data;
  OakSave__UITrackingSaveGameData *ui_tracking_save_game_data;
  char *preferred_character_name;
  int32_t name_character_limit;
  uint32_t preferred_group_mode;
  OakSave__TimeOfDaySaveGameData *time_of_day_save_game_data;
  size_t n_level_persistence_data;
  OakSave__LevelPersistenceLevelSaveGameData **level_persistence_data;
  uint32_t accumulated_level_persistence_reset_timer_seconds;
  uint32_t mayhem_level;
  OakSave__GbxZoneMapFODSaveGameData *gbx_zone_map_fod_save_game_data;
  size_t n_active_or_blacklisted_travel_stations;
  OakSave__ActiveFastTravelSaveData **active_or_blacklisted_travel_stations;
  size_t n_last_active_travel_station_for_playthrough;
  char **last_active_travel_station_for_playthrough;
  size_t n_game_state_save_data_for_playthrough;
  OakSave__GameStateSaveData **game_state_save_data_for_playthrough;
  size_t n_registered_downloadable_entitlements;
  OakSave__RegisteredDownloadableEntitlements **registered_downloadable_entitlements;
  size_t n_active_travel_stations_for_playthrough;
  OakSave__PlaythroughActiveFastTravelSaveData **active_travel_stations_for_playthrough;
  char *save_game_guid;
  OakSave__GuardianRankCharacterSaveGameData *guardian_rank_character_data;
  protobuf_c_boolean optional_objective_reward_fixup_applied;
  protobuf_c_boolean vehicle_part_rewards_fixup_applied;
  uint32_t last_active_league;
  uint32_t last_active_league_instance;
  size_t n_active_league_instance_for_event;
  OakSave__Character__ActiveLeagueInstanceForEventEntry **active_league_instance_for_event;
};
#define OAK_SAVE__CHARACTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&oak_save__character__descriptor) \
    , 0, 0, 0, NULL, 0,NULL, 0,NULL, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL, 0, 0, 0, 0,NULL, 0,NULL, NULL, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL, NULL, NULL, 0,NULL, 0, 0,NULL, NULL, NULL, NULL, NULL, (char *)protobuf_c_empty_string, 0, 0, NULL, 0,NULL, 0, 0, NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, NULL, 0, 0, 0, 0, 0,NULL }


/* OakSave__PlayerClassSaveGameData methods */
void   oak_save__player_class_save_game_data__init
                     (OakSave__PlayerClassSaveGameData         *message);
size_t oak_save__player_class_save_game_data__get_packed_size
                     (const OakSave__PlayerClassSaveGameData   *message);
size_t oak_save__player_class_save_game_data__pack
                     (const OakSave__PlayerClassSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__player_class_save_game_data__pack_to_buffer
                     (const OakSave__PlayerClassSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlayerClassSaveGameData *
       oak_save__player_class_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__player_class_save_game_data__free_unpacked
                     (OakSave__PlayerClassSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__ResourcePoolSavegameData methods */
void   oak_save__resource_pool_savegame_data__init
                     (OakSave__ResourcePoolSavegameData         *message);
size_t oak_save__resource_pool_savegame_data__get_packed_size
                     (const OakSave__ResourcePoolSavegameData   *message);
size_t oak_save__resource_pool_savegame_data__pack
                     (const OakSave__ResourcePoolSavegameData   *message,
                      uint8_t             *out);
size_t oak_save__resource_pool_savegame_data__pack_to_buffer
                     (const OakSave__ResourcePoolSavegameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__ResourcePoolSavegameData *
       oak_save__resource_pool_savegame_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__resource_pool_savegame_data__free_unpacked
                     (OakSave__ResourcePoolSavegameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__RegionSaveGameData methods */
void   oak_save__region_save_game_data__init
                     (OakSave__RegionSaveGameData         *message);
size_t oak_save__region_save_game_data__get_packed_size
                     (const OakSave__RegionSaveGameData   *message);
size_t oak_save__region_save_game_data__pack
                     (const OakSave__RegionSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__region_save_game_data__pack_to_buffer
                     (const OakSave__RegionSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__RegionSaveGameData *
       oak_save__region_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__region_save_game_data__free_unpacked
                     (OakSave__RegionSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__InventoryBalanceStateInitializationData methods */
void   oak_save__inventory_balance_state_initialization_data__init
                     (OakSave__InventoryBalanceStateInitializationData         *message);
size_t oak_save__inventory_balance_state_initialization_data__get_packed_size
                     (const OakSave__InventoryBalanceStateInitializationData   *message);
size_t oak_save__inventory_balance_state_initialization_data__pack
                     (const OakSave__InventoryBalanceStateInitializationData   *message,
                      uint8_t             *out);
size_t oak_save__inventory_balance_state_initialization_data__pack_to_buffer
                     (const OakSave__InventoryBalanceStateInitializationData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__InventoryBalanceStateInitializationData *
       oak_save__inventory_balance_state_initialization_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__inventory_balance_state_initialization_data__free_unpacked
                     (OakSave__InventoryBalanceStateInitializationData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakInventoryItemSaveGameData methods */
void   oak_save__oak_inventory_item_save_game_data__init
                     (OakSave__OakInventoryItemSaveGameData         *message);
size_t oak_save__oak_inventory_item_save_game_data__get_packed_size
                     (const OakSave__OakInventoryItemSaveGameData   *message);
size_t oak_save__oak_inventory_item_save_game_data__pack
                     (const OakSave__OakInventoryItemSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_inventory_item_save_game_data__pack_to_buffer
                     (const OakSave__OakInventoryItemSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakInventoryItemSaveGameData *
       oak_save__oak_inventory_item_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_inventory_item_save_game_data__free_unpacked
                     (OakSave__OakInventoryItemSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__EquippedInventorySaveGameData methods */
void   oak_save__equipped_inventory_save_game_data__init
                     (OakSave__EquippedInventorySaveGameData         *message);
size_t oak_save__equipped_inventory_save_game_data__get_packed_size
                     (const OakSave__EquippedInventorySaveGameData   *message);
size_t oak_save__equipped_inventory_save_game_data__pack
                     (const OakSave__EquippedInventorySaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__equipped_inventory_save_game_data__pack_to_buffer
                     (const OakSave__EquippedInventorySaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__EquippedInventorySaveGameData *
       oak_save__equipped_inventory_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__equipped_inventory_save_game_data__free_unpacked
                     (OakSave__EquippedInventorySaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakAbilityTreeItemSaveGameData methods */
void   oak_save__oak_ability_tree_item_save_game_data__init
                     (OakSave__OakAbilityTreeItemSaveGameData         *message);
size_t oak_save__oak_ability_tree_item_save_game_data__get_packed_size
                     (const OakSave__OakAbilityTreeItemSaveGameData   *message);
size_t oak_save__oak_ability_tree_item_save_game_data__pack
                     (const OakSave__OakAbilityTreeItemSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_ability_tree_item_save_game_data__pack_to_buffer
                     (const OakSave__OakAbilityTreeItemSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakAbilityTreeItemSaveGameData *
       oak_save__oak_ability_tree_item_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_ability_tree_item_save_game_data__free_unpacked
                     (OakSave__OakAbilityTreeItemSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakAbilitySlotSaveGameData methods */
void   oak_save__oak_ability_slot_save_game_data__init
                     (OakSave__OakAbilitySlotSaveGameData         *message);
size_t oak_save__oak_ability_slot_save_game_data__get_packed_size
                     (const OakSave__OakAbilitySlotSaveGameData   *message);
size_t oak_save__oak_ability_slot_save_game_data__pack
                     (const OakSave__OakAbilitySlotSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_ability_slot_save_game_data__pack_to_buffer
                     (const OakSave__OakAbilitySlotSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakAbilitySlotSaveGameData *
       oak_save__oak_ability_slot_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_ability_slot_save_game_data__free_unpacked
                     (OakSave__OakAbilitySlotSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakActionAbilityAugmentSaveGameData methods */
void   oak_save__oak_action_ability_augment_save_game_data__init
                     (OakSave__OakActionAbilityAugmentSaveGameData         *message);
size_t oak_save__oak_action_ability_augment_save_game_data__get_packed_size
                     (const OakSave__OakActionAbilityAugmentSaveGameData   *message);
size_t oak_save__oak_action_ability_augment_save_game_data__pack
                     (const OakSave__OakActionAbilityAugmentSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_action_ability_augment_save_game_data__pack_to_buffer
                     (const OakSave__OakActionAbilityAugmentSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakActionAbilityAugmentSaveGameData *
       oak_save__oak_action_ability_augment_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_action_ability_augment_save_game_data__free_unpacked
                     (OakSave__OakActionAbilityAugmentSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakActionAbilityAugmentConfigurationSaveGameData methods */
void   oak_save__oak_action_ability_augment_configuration_save_game_data__init
                     (OakSave__OakActionAbilityAugmentConfigurationSaveGameData         *message);
size_t oak_save__oak_action_ability_augment_configuration_save_game_data__get_packed_size
                     (const OakSave__OakActionAbilityAugmentConfigurationSaveGameData   *message);
size_t oak_save__oak_action_ability_augment_configuration_save_game_data__pack
                     (const OakSave__OakActionAbilityAugmentConfigurationSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_action_ability_augment_configuration_save_game_data__pack_to_buffer
                     (const OakSave__OakActionAbilityAugmentConfigurationSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakActionAbilityAugmentConfigurationSaveGameData *
       oak_save__oak_action_ability_augment_configuration_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_action_ability_augment_configuration_save_game_data__free_unpacked
                     (OakSave__OakActionAbilityAugmentConfigurationSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakPlayerAbilitySaveGameData methods */
void   oak_save__oak_player_ability_save_game_data__init
                     (OakSave__OakPlayerAbilitySaveGameData         *message);
size_t oak_save__oak_player_ability_save_game_data__get_packed_size
                     (const OakSave__OakPlayerAbilitySaveGameData   *message);
size_t oak_save__oak_player_ability_save_game_data__pack
                     (const OakSave__OakPlayerAbilitySaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_player_ability_save_game_data__pack_to_buffer
                     (const OakSave__OakPlayerAbilitySaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakPlayerAbilitySaveGameData *
       oak_save__oak_player_ability_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_player_ability_save_game_data__free_unpacked
                     (OakSave__OakPlayerAbilitySaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__MissionStatusPlayerSaveGameData methods */
void   oak_save__mission_status_player_save_game_data__init
                     (OakSave__MissionStatusPlayerSaveGameData         *message);
size_t oak_save__mission_status_player_save_game_data__get_packed_size
                     (const OakSave__MissionStatusPlayerSaveGameData   *message);
size_t oak_save__mission_status_player_save_game_data__pack
                     (const OakSave__MissionStatusPlayerSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__mission_status_player_save_game_data__pack_to_buffer
                     (const OakSave__MissionStatusPlayerSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__MissionStatusPlayerSaveGameData *
       oak_save__mission_status_player_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__mission_status_player_save_game_data__free_unpacked
                     (OakSave__MissionStatusPlayerSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__MissionPlaythroughSaveGameData methods */
void   oak_save__mission_playthrough_save_game_data__init
                     (OakSave__MissionPlaythroughSaveGameData         *message);
size_t oak_save__mission_playthrough_save_game_data__get_packed_size
                     (const OakSave__MissionPlaythroughSaveGameData   *message);
size_t oak_save__mission_playthrough_save_game_data__pack
                     (const OakSave__MissionPlaythroughSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__mission_playthrough_save_game_data__pack_to_buffer
                     (const OakSave__MissionPlaythroughSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__MissionPlaythroughSaveGameData *
       oak_save__mission_playthrough_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__mission_playthrough_save_game_data__free_unpacked
                     (OakSave__MissionPlaythroughSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__ActiveFastTravelSaveData methods */
void   oak_save__active_fast_travel_save_data__init
                     (OakSave__ActiveFastTravelSaveData         *message);
size_t oak_save__active_fast_travel_save_data__get_packed_size
                     (const OakSave__ActiveFastTravelSaveData   *message);
size_t oak_save__active_fast_travel_save_data__pack
                     (const OakSave__ActiveFastTravelSaveData   *message,
                      uint8_t             *out);
size_t oak_save__active_fast_travel_save_data__pack_to_buffer
                     (const OakSave__ActiveFastTravelSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__ActiveFastTravelSaveData *
       oak_save__active_fast_travel_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__active_fast_travel_save_data__free_unpacked
                     (OakSave__ActiveFastTravelSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__PlaythroughActiveFastTravelSaveData methods */
void   oak_save__playthrough_active_fast_travel_save_data__init
                     (OakSave__PlaythroughActiveFastTravelSaveData         *message);
size_t oak_save__playthrough_active_fast_travel_save_data__get_packed_size
                     (const OakSave__PlaythroughActiveFastTravelSaveData   *message);
size_t oak_save__playthrough_active_fast_travel_save_data__pack
                     (const OakSave__PlaythroughActiveFastTravelSaveData   *message,
                      uint8_t             *out);
size_t oak_save__playthrough_active_fast_travel_save_data__pack_to_buffer
                     (const OakSave__PlaythroughActiveFastTravelSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlaythroughActiveFastTravelSaveData *
       oak_save__playthrough_active_fast_travel_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__playthrough_active_fast_travel_save_data__free_unpacked
                     (OakSave__PlaythroughActiveFastTravelSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__DiscoveredAreaInfo methods */
void   oak_save__discovered_area_info__init
                     (OakSave__DiscoveredAreaInfo         *message);
size_t oak_save__discovered_area_info__get_packed_size
                     (const OakSave__DiscoveredAreaInfo   *message);
size_t oak_save__discovered_area_info__pack
                     (const OakSave__DiscoveredAreaInfo   *message,
                      uint8_t             *out);
size_t oak_save__discovered_area_info__pack_to_buffer
                     (const OakSave__DiscoveredAreaInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__DiscoveredAreaInfo *
       oak_save__discovered_area_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__discovered_area_info__free_unpacked
                     (OakSave__DiscoveredAreaInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__DiscoveredLevelInfo methods */
void   oak_save__discovered_level_info__init
                     (OakSave__DiscoveredLevelInfo         *message);
size_t oak_save__discovered_level_info__get_packed_size
                     (const OakSave__DiscoveredLevelInfo   *message);
size_t oak_save__discovered_level_info__pack
                     (const OakSave__DiscoveredLevelInfo   *message,
                      uint8_t             *out);
size_t oak_save__discovered_level_info__pack_to_buffer
                     (const OakSave__DiscoveredLevelInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__DiscoveredLevelInfo *
       oak_save__discovered_level_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__discovered_level_info__free_unpacked
                     (OakSave__DiscoveredLevelInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__DiscoveredPlanetInfo methods */
void   oak_save__discovered_planet_info__init
                     (OakSave__DiscoveredPlanetInfo         *message);
size_t oak_save__discovered_planet_info__get_packed_size
                     (const OakSave__DiscoveredPlanetInfo   *message);
size_t oak_save__discovered_planet_info__pack
                     (const OakSave__DiscoveredPlanetInfo   *message,
                      uint8_t             *out);
size_t oak_save__discovered_planet_info__pack_to_buffer
                     (const OakSave__DiscoveredPlanetInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__DiscoveredPlanetInfo *
       oak_save__discovered_planet_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__discovered_planet_info__free_unpacked
                     (OakSave__DiscoveredPlanetInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__DiscoverySaveData methods */
void   oak_save__discovery_save_data__init
                     (OakSave__DiscoverySaveData         *message);
size_t oak_save__discovery_save_data__get_packed_size
                     (const OakSave__DiscoverySaveData   *message);
size_t oak_save__discovery_save_data__pack
                     (const OakSave__DiscoverySaveData   *message,
                      uint8_t             *out);
size_t oak_save__discovery_save_data__pack_to_buffer
                     (const OakSave__DiscoverySaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__DiscoverySaveData *
       oak_save__discovery_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__discovery_save_data__free_unpacked
                     (OakSave__DiscoverySaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__VehicleUnlockedSaveGameData methods */
void   oak_save__vehicle_unlocked_save_game_data__init
                     (OakSave__VehicleUnlockedSaveGameData         *message);
size_t oak_save__vehicle_unlocked_save_game_data__get_packed_size
                     (const OakSave__VehicleUnlockedSaveGameData   *message);
size_t oak_save__vehicle_unlocked_save_game_data__pack
                     (const OakSave__VehicleUnlockedSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__vehicle_unlocked_save_game_data__pack_to_buffer
                     (const OakSave__VehicleUnlockedSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__VehicleUnlockedSaveGameData *
       oak_save__vehicle_unlocked_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__vehicle_unlocked_save_game_data__free_unpacked
                     (OakSave__VehicleUnlockedSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakCARMenuVehicleConfigSaveData methods */
void   oak_save__oak_carmenu_vehicle_config_save_data__init
                     (OakSave__OakCARMenuVehicleConfigSaveData         *message);
size_t oak_save__oak_carmenu_vehicle_config_save_data__get_packed_size
                     (const OakSave__OakCARMenuVehicleConfigSaveData   *message);
size_t oak_save__oak_carmenu_vehicle_config_save_data__pack
                     (const OakSave__OakCARMenuVehicleConfigSaveData   *message,
                      uint8_t             *out);
size_t oak_save__oak_carmenu_vehicle_config_save_data__pack_to_buffer
                     (const OakSave__OakCARMenuVehicleConfigSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakCARMenuVehicleConfigSaveData *
       oak_save__oak_carmenu_vehicle_config_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_carmenu_vehicle_config_save_data__free_unpacked
                     (OakSave__OakCARMenuVehicleConfigSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CustomPlayerColorSaveGameData methods */
void   oak_save__custom_player_color_save_game_data__init
                     (OakSave__CustomPlayerColorSaveGameData         *message);
size_t oak_save__custom_player_color_save_game_data__get_packed_size
                     (const OakSave__CustomPlayerColorSaveGameData   *message);
size_t oak_save__custom_player_color_save_game_data__pack
                     (const OakSave__CustomPlayerColorSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__custom_player_color_save_game_data__pack_to_buffer
                     (const OakSave__CustomPlayerColorSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CustomPlayerColorSaveGameData *
       oak_save__custom_player_color_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__custom_player_color_save_game_data__free_unpacked
                     (OakSave__CustomPlayerColorSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GuardianRankSaveGameData methods */
void   oak_save__guardian_rank_save_game_data__init
                     (OakSave__GuardianRankSaveGameData         *message);
size_t oak_save__guardian_rank_save_game_data__get_packed_size
                     (const OakSave__GuardianRankSaveGameData   *message);
size_t oak_save__guardian_rank_save_game_data__pack
                     (const OakSave__GuardianRankSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__guardian_rank_save_game_data__pack_to_buffer
                     (const OakSave__GuardianRankSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GuardianRankSaveGameData *
       oak_save__guardian_rank_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__guardian_rank_save_game_data__free_unpacked
                     (OakSave__GuardianRankSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GuardianRankRewardCharacterSaveGameData methods */
void   oak_save__guardian_rank_reward_character_save_game_data__init
                     (OakSave__GuardianRankRewardCharacterSaveGameData         *message);
size_t oak_save__guardian_rank_reward_character_save_game_data__get_packed_size
                     (const OakSave__GuardianRankRewardCharacterSaveGameData   *message);
size_t oak_save__guardian_rank_reward_character_save_game_data__pack
                     (const OakSave__GuardianRankRewardCharacterSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__guardian_rank_reward_character_save_game_data__pack_to_buffer
                     (const OakSave__GuardianRankRewardCharacterSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GuardianRankRewardCharacterSaveGameData *
       oak_save__guardian_rank_reward_character_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__guardian_rank_reward_character_save_game_data__free_unpacked
                     (OakSave__GuardianRankRewardCharacterSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GuardianRankPerkCharacterSaveGameData methods */
void   oak_save__guardian_rank_perk_character_save_game_data__init
                     (OakSave__GuardianRankPerkCharacterSaveGameData         *message);
size_t oak_save__guardian_rank_perk_character_save_game_data__get_packed_size
                     (const OakSave__GuardianRankPerkCharacterSaveGameData   *message);
size_t oak_save__guardian_rank_perk_character_save_game_data__pack
                     (const OakSave__GuardianRankPerkCharacterSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__guardian_rank_perk_character_save_game_data__pack_to_buffer
                     (const OakSave__GuardianRankPerkCharacterSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GuardianRankPerkCharacterSaveGameData *
       oak_save__guardian_rank_perk_character_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__guardian_rank_perk_character_save_game_data__free_unpacked
                     (OakSave__GuardianRankPerkCharacterSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GuardianRankCharacterSaveGameData methods */
void   oak_save__guardian_rank_character_save_game_data__init
                     (OakSave__GuardianRankCharacterSaveGameData         *message);
size_t oak_save__guardian_rank_character_save_game_data__get_packed_size
                     (const OakSave__GuardianRankCharacterSaveGameData   *message);
size_t oak_save__guardian_rank_character_save_game_data__pack
                     (const OakSave__GuardianRankCharacterSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__guardian_rank_character_save_game_data__pack_to_buffer
                     (const OakSave__GuardianRankCharacterSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GuardianRankCharacterSaveGameData *
       oak_save__guardian_rank_character_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__guardian_rank_character_save_game_data__free_unpacked
                     (OakSave__GuardianRankCharacterSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CrewQuartersDecorationSaveData methods */
void   oak_save__crew_quarters_decoration_save_data__init
                     (OakSave__CrewQuartersDecorationSaveData         *message);
size_t oak_save__crew_quarters_decoration_save_data__get_packed_size
                     (const OakSave__CrewQuartersDecorationSaveData   *message);
size_t oak_save__crew_quarters_decoration_save_data__pack
                     (const OakSave__CrewQuartersDecorationSaveData   *message,
                      uint8_t             *out);
size_t oak_save__crew_quarters_decoration_save_data__pack_to_buffer
                     (const OakSave__CrewQuartersDecorationSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CrewQuartersDecorationSaveData *
       oak_save__crew_quarters_decoration_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__crew_quarters_decoration_save_data__free_unpacked
                     (OakSave__CrewQuartersDecorationSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CrewQuartersSaveData methods */
void   oak_save__crew_quarters_save_data__init
                     (OakSave__CrewQuartersSaveData         *message);
size_t oak_save__crew_quarters_save_data__get_packed_size
                     (const OakSave__CrewQuartersSaveData   *message);
size_t oak_save__crew_quarters_save_data__pack
                     (const OakSave__CrewQuartersSaveData   *message,
                      uint8_t             *out);
size_t oak_save__crew_quarters_save_data__pack_to_buffer
                     (const OakSave__CrewQuartersSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CrewQuartersSaveData *
       oak_save__crew_quarters_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__crew_quarters_save_data__free_unpacked
                     (OakSave__CrewQuartersSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CrewQuartersGunRackItemSaveData methods */
void   oak_save__crew_quarters_gun_rack_item_save_data__init
                     (OakSave__CrewQuartersGunRackItemSaveData         *message);
size_t oak_save__crew_quarters_gun_rack_item_save_data__get_packed_size
                     (const OakSave__CrewQuartersGunRackItemSaveData   *message);
size_t oak_save__crew_quarters_gun_rack_item_save_data__pack
                     (const OakSave__CrewQuartersGunRackItemSaveData   *message,
                      uint8_t             *out);
size_t oak_save__crew_quarters_gun_rack_item_save_data__pack_to_buffer
                     (const OakSave__CrewQuartersGunRackItemSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CrewQuartersGunRackItemSaveData *
       oak_save__crew_quarters_gun_rack_item_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__crew_quarters_gun_rack_item_save_data__free_unpacked
                     (OakSave__CrewQuartersGunRackItemSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__CrewQuartersGunRackSaveData methods */
void   oak_save__crew_quarters_gun_rack_save_data__init
                     (OakSave__CrewQuartersGunRackSaveData         *message);
size_t oak_save__crew_quarters_gun_rack_save_data__get_packed_size
                     (const OakSave__CrewQuartersGunRackSaveData   *message);
size_t oak_save__crew_quarters_gun_rack_save_data__pack
                     (const OakSave__CrewQuartersGunRackSaveData   *message,
                      uint8_t             *out);
size_t oak_save__crew_quarters_gun_rack_save_data__pack_to_buffer
                     (const OakSave__CrewQuartersGunRackSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__CrewQuartersGunRackSaveData *
       oak_save__crew_quarters_gun_rack_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__crew_quarters_gun_rack_save_data__free_unpacked
                     (OakSave__CrewQuartersGunRackSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__EchoLogSaveGameData methods */
void   oak_save__echo_log_save_game_data__init
                     (OakSave__EchoLogSaveGameData         *message);
size_t oak_save__echo_log_save_game_data__get_packed_size
                     (const OakSave__EchoLogSaveGameData   *message);
size_t oak_save__echo_log_save_game_data__pack
                     (const OakSave__EchoLogSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__echo_log_save_game_data__pack_to_buffer
                     (const OakSave__EchoLogSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__EchoLogSaveGameData *
       oak_save__echo_log_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__echo_log_save_game_data__free_unpacked
                     (OakSave__EchoLogSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__MapIDData methods */
void   oak_save__map_iddata__init
                     (OakSave__MapIDData         *message);
size_t oak_save__map_iddata__get_packed_size
                     (const OakSave__MapIDData   *message);
size_t oak_save__map_iddata__pack
                     (const OakSave__MapIDData   *message,
                      uint8_t             *out);
size_t oak_save__map_iddata__pack_to_buffer
                     (const OakSave__MapIDData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__MapIDData *
       oak_save__map_iddata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__map_iddata__free_unpacked
                     (OakSave__MapIDData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GameStateSaveData methods */
void   oak_save__game_state_save_data__init
                     (OakSave__GameStateSaveData         *message);
size_t oak_save__game_state_save_data__get_packed_size
                     (const OakSave__GameStateSaveData   *message);
size_t oak_save__game_state_save_data__pack
                     (const OakSave__GameStateSaveData   *message,
                      uint8_t             *out);
size_t oak_save__game_state_save_data__pack_to_buffer
                     (const OakSave__GameStateSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GameStateSaveData *
       oak_save__game_state_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__game_state_save_data__free_unpacked
                     (OakSave__GameStateSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__ChallengeCategoryProgressSaveData methods */
void   oak_save__challenge_category_progress_save_data__init
                     (OakSave__ChallengeCategoryProgressSaveData         *message);
size_t oak_save__challenge_category_progress_save_data__get_packed_size
                     (const OakSave__ChallengeCategoryProgressSaveData   *message);
size_t oak_save__challenge_category_progress_save_data__pack
                     (const OakSave__ChallengeCategoryProgressSaveData   *message,
                      uint8_t             *out);
size_t oak_save__challenge_category_progress_save_data__pack_to_buffer
                     (const OakSave__ChallengeCategoryProgressSaveData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__ChallengeCategoryProgressSaveData *
       oak_save__challenge_category_progress_save_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__challenge_category_progress_save_data__free_unpacked
                     (OakSave__ChallengeCategoryProgressSaveData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakPlayerCharacterAugmentSaveGameData methods */
void   oak_save__oak_player_character_augment_save_game_data__init
                     (OakSave__OakPlayerCharacterAugmentSaveGameData         *message);
size_t oak_save__oak_player_character_augment_save_game_data__get_packed_size
                     (const OakSave__OakPlayerCharacterAugmentSaveGameData   *message);
size_t oak_save__oak_player_character_augment_save_game_data__pack
                     (const OakSave__OakPlayerCharacterAugmentSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_player_character_augment_save_game_data__pack_to_buffer
                     (const OakSave__OakPlayerCharacterAugmentSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakPlayerCharacterAugmentSaveGameData *
       oak_save__oak_player_character_augment_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_player_character_augment_save_game_data__free_unpacked
                     (OakSave__OakPlayerCharacterAugmentSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__OakPlayerCharacterSlotSaveGameData methods */
void   oak_save__oak_player_character_slot_save_game_data__init
                     (OakSave__OakPlayerCharacterSlotSaveGameData         *message);
size_t oak_save__oak_player_character_slot_save_game_data__get_packed_size
                     (const OakSave__OakPlayerCharacterSlotSaveGameData   *message);
size_t oak_save__oak_player_character_slot_save_game_data__pack
                     (const OakSave__OakPlayerCharacterSlotSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__oak_player_character_slot_save_game_data__pack_to_buffer
                     (const OakSave__OakPlayerCharacterSlotSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__OakPlayerCharacterSlotSaveGameData *
       oak_save__oak_player_character_slot_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__oak_player_character_slot_save_game_data__free_unpacked
                     (OakSave__OakPlayerCharacterSlotSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__UITrackingSaveGameData methods */
void   oak_save__uitracking_save_game_data__init
                     (OakSave__UITrackingSaveGameData         *message);
size_t oak_save__uitracking_save_game_data__get_packed_size
                     (const OakSave__UITrackingSaveGameData   *message);
size_t oak_save__uitracking_save_game_data__pack
                     (const OakSave__UITrackingSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__uitracking_save_game_data__pack_to_buffer
                     (const OakSave__UITrackingSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__UITrackingSaveGameData *
       oak_save__uitracking_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__uitracking_save_game_data__free_unpacked
                     (OakSave__UITrackingSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__PlanetCycleInfo methods */
void   oak_save__planet_cycle_info__init
                     (OakSave__PlanetCycleInfo         *message);
size_t oak_save__planet_cycle_info__get_packed_size
                     (const OakSave__PlanetCycleInfo   *message);
size_t oak_save__planet_cycle_info__pack
                     (const OakSave__PlanetCycleInfo   *message,
                      uint8_t             *out);
size_t oak_save__planet_cycle_info__pack_to_buffer
                     (const OakSave__PlanetCycleInfo   *message,
                      ProtobufCBuffer     *buffer);
OakSave__PlanetCycleInfo *
       oak_save__planet_cycle_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__planet_cycle_info__free_unpacked
                     (OakSave__PlanetCycleInfo *message,
                      ProtobufCAllocator *allocator);
/* OakSave__TimeOfDaySaveGameData methods */
void   oak_save__time_of_day_save_game_data__init
                     (OakSave__TimeOfDaySaveGameData         *message);
size_t oak_save__time_of_day_save_game_data__get_packed_size
                     (const OakSave__TimeOfDaySaveGameData   *message);
size_t oak_save__time_of_day_save_game_data__pack
                     (const OakSave__TimeOfDaySaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__time_of_day_save_game_data__pack_to_buffer
                     (const OakSave__TimeOfDaySaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__TimeOfDaySaveGameData *
       oak_save__time_of_day_save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__time_of_day_save_game_data__free_unpacked
                     (OakSave__TimeOfDaySaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__LevelPersistenceActorSaveGameData methods */
void   oak_save__level_persistence__actor__save_game_data__init
                     (OakSave__LevelPersistenceActorSaveGameData         *message);
size_t oak_save__level_persistence__actor__save_game_data__get_packed_size
                     (const OakSave__LevelPersistenceActorSaveGameData   *message);
size_t oak_save__level_persistence__actor__save_game_data__pack
                     (const OakSave__LevelPersistenceActorSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__level_persistence__actor__save_game_data__pack_to_buffer
                     (const OakSave__LevelPersistenceActorSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__LevelPersistenceActorSaveGameData *
       oak_save__level_persistence__actor__save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__level_persistence__actor__save_game_data__free_unpacked
                     (OakSave__LevelPersistenceActorSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__LevelPersistenceLevelSaveGameData methods */
void   oak_save__level_persistence__level__save_game_data__init
                     (OakSave__LevelPersistenceLevelSaveGameData         *message);
size_t oak_save__level_persistence__level__save_game_data__get_packed_size
                     (const OakSave__LevelPersistenceLevelSaveGameData   *message);
size_t oak_save__level_persistence__level__save_game_data__pack
                     (const OakSave__LevelPersistenceLevelSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__level_persistence__level__save_game_data__pack_to_buffer
                     (const OakSave__LevelPersistenceLevelSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__LevelPersistenceLevelSaveGameData *
       oak_save__level_persistence__level__save_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__level_persistence__level__save_game_data__free_unpacked
                     (OakSave__LevelPersistenceLevelSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GbxZoneMapFODSavedLevelData methods */
void   oak_save__gbx_zone_map_fodsaved_level_data__init
                     (OakSave__GbxZoneMapFODSavedLevelData         *message);
size_t oak_save__gbx_zone_map_fodsaved_level_data__get_packed_size
                     (const OakSave__GbxZoneMapFODSavedLevelData   *message);
size_t oak_save__gbx_zone_map_fodsaved_level_data__pack
                     (const OakSave__GbxZoneMapFODSavedLevelData   *message,
                      uint8_t             *out);
size_t oak_save__gbx_zone_map_fodsaved_level_data__pack_to_buffer
                     (const OakSave__GbxZoneMapFODSavedLevelData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GbxZoneMapFODSavedLevelData *
       oak_save__gbx_zone_map_fodsaved_level_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__gbx_zone_map_fodsaved_level_data__free_unpacked
                     (OakSave__GbxZoneMapFODSavedLevelData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__GbxZoneMapFODSaveGameData methods */
void   oak_save__gbx_zone_map_fodsave_game_data__init
                     (OakSave__GbxZoneMapFODSaveGameData         *message);
size_t oak_save__gbx_zone_map_fodsave_game_data__get_packed_size
                     (const OakSave__GbxZoneMapFODSaveGameData   *message);
size_t oak_save__gbx_zone_map_fodsave_game_data__pack
                     (const OakSave__GbxZoneMapFODSaveGameData   *message,
                      uint8_t             *out);
size_t oak_save__gbx_zone_map_fodsave_game_data__pack_to_buffer
                     (const OakSave__GbxZoneMapFODSaveGameData   *message,
                      ProtobufCBuffer     *buffer);
OakSave__GbxZoneMapFODSaveGameData *
       oak_save__gbx_zone_map_fodsave_game_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__gbx_zone_map_fodsave_game_data__free_unpacked
                     (OakSave__GbxZoneMapFODSaveGameData *message,
                      ProtobufCAllocator *allocator);
/* OakSave__Character__NicknameMappingsEntry methods */
void   oak_save__character__nickname_mappings_entry__init
                     (OakSave__Character__NicknameMappingsEntry         *message);
/* OakSave__Character__ActiveLeagueInstanceForEventEntry methods */
void   oak_save__character__active_league_instance_for_event_entry__init
                     (OakSave__Character__ActiveLeagueInstanceForEventEntry         *message);
/* OakSave__Character methods */
void   oak_save__character__init
                     (OakSave__Character         *message);
size_t oak_save__character__get_packed_size
                     (const OakSave__Character   *message);
size_t oak_save__character__pack
                     (const OakSave__Character   *message,
                      uint8_t             *out);
size_t oak_save__character__pack_to_buffer
                     (const OakSave__Character   *message,
                      ProtobufCBuffer     *buffer);
OakSave__Character *
       oak_save__character__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   oak_save__character__free_unpacked
                     (OakSave__Character *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*OakSave__PlayerClassSaveGameData_Closure)
                 (const OakSave__PlayerClassSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__ResourcePoolSavegameData_Closure)
                 (const OakSave__ResourcePoolSavegameData *message,
                  void *closure_data);
typedef void (*OakSave__RegionSaveGameData_Closure)
                 (const OakSave__RegionSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__InventoryBalanceStateInitializationData_Closure)
                 (const OakSave__InventoryBalanceStateInitializationData *message,
                  void *closure_data);
typedef void (*OakSave__OakInventoryItemSaveGameData_Closure)
                 (const OakSave__OakInventoryItemSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__EquippedInventorySaveGameData_Closure)
                 (const OakSave__EquippedInventorySaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakAbilityTreeItemSaveGameData_Closure)
                 (const OakSave__OakAbilityTreeItemSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakAbilitySlotSaveGameData_Closure)
                 (const OakSave__OakAbilitySlotSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakActionAbilityAugmentSaveGameData_Closure)
                 (const OakSave__OakActionAbilityAugmentSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakActionAbilityAugmentConfigurationSaveGameData_Closure)
                 (const OakSave__OakActionAbilityAugmentConfigurationSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakPlayerAbilitySaveGameData_Closure)
                 (const OakSave__OakPlayerAbilitySaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__MissionStatusPlayerSaveGameData_Closure)
                 (const OakSave__MissionStatusPlayerSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__MissionPlaythroughSaveGameData_Closure)
                 (const OakSave__MissionPlaythroughSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__ActiveFastTravelSaveData_Closure)
                 (const OakSave__ActiveFastTravelSaveData *message,
                  void *closure_data);
typedef void (*OakSave__PlaythroughActiveFastTravelSaveData_Closure)
                 (const OakSave__PlaythroughActiveFastTravelSaveData *message,
                  void *closure_data);
typedef void (*OakSave__DiscoveredAreaInfo_Closure)
                 (const OakSave__DiscoveredAreaInfo *message,
                  void *closure_data);
typedef void (*OakSave__DiscoveredLevelInfo_Closure)
                 (const OakSave__DiscoveredLevelInfo *message,
                  void *closure_data);
typedef void (*OakSave__DiscoveredPlanetInfo_Closure)
                 (const OakSave__DiscoveredPlanetInfo *message,
                  void *closure_data);
typedef void (*OakSave__DiscoverySaveData_Closure)
                 (const OakSave__DiscoverySaveData *message,
                  void *closure_data);
typedef void (*OakSave__VehicleUnlockedSaveGameData_Closure)
                 (const OakSave__VehicleUnlockedSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakCARMenuVehicleConfigSaveData_Closure)
                 (const OakSave__OakCARMenuVehicleConfigSaveData *message,
                  void *closure_data);
typedef void (*OakSave__CustomPlayerColorSaveGameData_Closure)
                 (const OakSave__CustomPlayerColorSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__GuardianRankSaveGameData_Closure)
                 (const OakSave__GuardianRankSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__GuardianRankRewardCharacterSaveGameData_Closure)
                 (const OakSave__GuardianRankRewardCharacterSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__GuardianRankPerkCharacterSaveGameData_Closure)
                 (const OakSave__GuardianRankPerkCharacterSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__GuardianRankCharacterSaveGameData_Closure)
                 (const OakSave__GuardianRankCharacterSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__CrewQuartersDecorationSaveData_Closure)
                 (const OakSave__CrewQuartersDecorationSaveData *message,
                  void *closure_data);
typedef void (*OakSave__CrewQuartersSaveData_Closure)
                 (const OakSave__CrewQuartersSaveData *message,
                  void *closure_data);
typedef void (*OakSave__CrewQuartersGunRackItemSaveData_Closure)
                 (const OakSave__CrewQuartersGunRackItemSaveData *message,
                  void *closure_data);
typedef void (*OakSave__CrewQuartersGunRackSaveData_Closure)
                 (const OakSave__CrewQuartersGunRackSaveData *message,
                  void *closure_data);
typedef void (*OakSave__EchoLogSaveGameData_Closure)
                 (const OakSave__EchoLogSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__MapIDData_Closure)
                 (const OakSave__MapIDData *message,
                  void *closure_data);
typedef void (*OakSave__GameStateSaveData_Closure)
                 (const OakSave__GameStateSaveData *message,
                  void *closure_data);
typedef void (*OakSave__ChallengeCategoryProgressSaveData_Closure)
                 (const OakSave__ChallengeCategoryProgressSaveData *message,
                  void *closure_data);
typedef void (*OakSave__OakPlayerCharacterAugmentSaveGameData_Closure)
                 (const OakSave__OakPlayerCharacterAugmentSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__OakPlayerCharacterSlotSaveGameData_Closure)
                 (const OakSave__OakPlayerCharacterSlotSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__UITrackingSaveGameData_Closure)
                 (const OakSave__UITrackingSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__PlanetCycleInfo_Closure)
                 (const OakSave__PlanetCycleInfo *message,
                  void *closure_data);
typedef void (*OakSave__TimeOfDaySaveGameData_Closure)
                 (const OakSave__TimeOfDaySaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__LevelPersistenceActorSaveGameData_Closure)
                 (const OakSave__LevelPersistenceActorSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__LevelPersistenceLevelSaveGameData_Closure)
                 (const OakSave__LevelPersistenceLevelSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__GbxZoneMapFODSavedLevelData_Closure)
                 (const OakSave__GbxZoneMapFODSavedLevelData *message,
                  void *closure_data);
typedef void (*OakSave__GbxZoneMapFODSaveGameData_Closure)
                 (const OakSave__GbxZoneMapFODSaveGameData *message,
                  void *closure_data);
typedef void (*OakSave__Character__NicknameMappingsEntry_Closure)
                 (const OakSave__Character__NicknameMappingsEntry *message,
                  void *closure_data);
typedef void (*OakSave__Character__ActiveLeagueInstanceForEventEntry_Closure)
                 (const OakSave__Character__ActiveLeagueInstanceForEventEntry *message,
                  void *closure_data);
typedef void (*OakSave__Character_Closure)
                 (const OakSave__Character *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor oak_save__player_class_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__resource_pool_savegame_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__region_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__inventory_balance_state_initialization_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_inventory_item_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__equipped_inventory_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_ability_tree_item_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_ability_slot_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_action_ability_augment_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_action_ability_augment_configuration_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_player_ability_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__mission_status_player_save_game_data__descriptor;
extern const ProtobufCEnumDescriptor    oak_save__mission_status_player_save_game_data__mission_state__descriptor;
extern const ProtobufCMessageDescriptor oak_save__mission_playthrough_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__active_fast_travel_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__playthrough_active_fast_travel_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__discovered_area_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__discovered_level_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__discovered_planet_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__discovery_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__vehicle_unlocked_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_carmenu_vehicle_config_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__custom_player_color_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__guardian_rank_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__guardian_rank_reward_character_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__guardian_rank_perk_character_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__guardian_rank_character_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__crew_quarters_decoration_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__crew_quarters_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__crew_quarters_gun_rack_item_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__crew_quarters_gun_rack_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__echo_log_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__map_iddata__descriptor;
extern const ProtobufCMessageDescriptor oak_save__game_state_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__challenge_category_progress_save_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_player_character_augment_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__oak_player_character_slot_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__uitracking_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__planet_cycle_info__descriptor;
extern const ProtobufCMessageDescriptor oak_save__time_of_day_save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__level_persistence__actor__save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__level_persistence__level__save_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__gbx_zone_map_fodsaved_level_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__gbx_zone_map_fodsave_game_data__descriptor;
extern const ProtobufCMessageDescriptor oak_save__character__descriptor;
extern const ProtobufCMessageDescriptor oak_save__character__nickname_mappings_entry__descriptor;
extern const ProtobufCMessageDescriptor oak_save__character__active_league_instance_for_event_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_OakSave_2eproto__INCLUDED */
